// AUTO-GENERATED by tools/build_registry.py - do not edit by hand.
export const GAME_LIST = [
{
"id": "hell-maze",
"n": 1,
"title": "HELL MAZE",
"genre": "horror",
"desc": "Find the key, reach the exit. Something wakes up in the maze the moment you move, and it knows the way.",
"controls": "Arrow keys / WASD to move",
"scoreLabel": "MAZES",
"tasks": [
{
"stat": "score",
"target": 3,
"text": "Escape 3 mazes in Hell Maze"
}
],
"file": "games/2d/hell-maze.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/hell-maze.png"
},
{
"id": "the-house",
"n": 2,
"title": "THE HOUSE",
"genre": "horror",
"desc": "Find the 5 lost photos in a dark house and get out the front door. A ghost drifts through the walls. Hide in a wardrobe when it comes.",
"controls": "WASD / arrows move · E hide in a wardrobe",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "photos",
"target": 5,
"text": "Find all 5 photos in The House"
}
],
"file": "games/2d/the-house.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/the-house.png"
},
{
"id": "wrong-neighbour",
"n": 3,
"title": "WRONG NEIGHBOUR",
"genre": "horror",
"desc": "It's 2 AM. Someone knocks. Compare them with the residents book: one tiny difference means it isn't who it says it is. Open for real neighbours, never for the others.",
"controls": "O or click OPEN · K or click KEEP SHUT",
"scoreLabel": "VISITORS",
"tasks": [
{
"stat": "score",
"target": 10,
"text": "Judge 10 visitors right in Wrong Neighbour"
}
],
"file": "games/2d/wrong-neighbour.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/wrong-neighbour.png"
},
{
"id": "observation-ward",
"n": 4,
"title": "OBSERVATION WARD",
"genre": "horror",
"desc": "Watch four hospital rooms through the cameras from midnight to 6 AM. Things move, vanish or appear. Click whatever changed to report it. Four unreported anomalies and the ward is lost.",
"controls": "1-4 or arrows switch camera · click the thing that changed",
"scoreLabel": "REPORTS",
"tasks": [
{
"stat": "score",
"target": 12,
"text": "Report 12 anomalies in Observation Ward"
}
],
"file": "games/2d/observation-ward.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/observation-ward.png"
},
{
"id": "night-watch",
"n": 5,
"title": "NIGHT WATCH",
"genre": "horror",
"desc": "Night guard at an old toy factory. Three things walk the halls toward your office. Check the cameras, flash the door lights, slam the doors. The power won't last if you panic.",
"controls": "A / D close left / right door · Q / E door lights · SPACE cameras",
"scoreLabel": "HOURS",
"tasks": [
{
"stat": "score",
"target": 6,
"text": "Survive until 6 AM in Night Watch"
}
],
"file": "games/2d/night-watch.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/night-watch.png"
},
{
"id": "flashlight",
"n": 6,
"title": "FLASHLIGHT",
"genre": "horror",
"desc": "Lost in a black forest with one torch. Shadows crawl toward you from the dark and burn away in the beam, but the battery drains. Grab spare batteries and survive as long as you can.",
"controls": "WASD move · mouse aims the torch · right click / F toggles it",
"scoreLabel": "SECONDS",
"tasks": [
{
"stat": "score",
"target": 90,
"text": "Survive 90 seconds in Flashlight"
}
],
"file": "games/2d/flashlight.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/flashlight.png"
},
{
"id": "dont-look-back",
"n": 7,
"title": "DON'T LOOK BACK",
"genre": "horror",
"desc": "A statue follows you through the ruins. It only moves when you are not looking at it. Light all the candles while keeping it in sight.",
"controls": "WASD move · mouse = where you look",
"scoreLabel": "CANDLES",
"tasks": [
{
"stat": "score",
"target": 8,
"text": "Light 8 candles in Don't Look Back"
}
],
"file": "games/2d/dont-look-back.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/dont-look-back.png"
},
{
"id": "last-train",
"n": 8,
"title": "LAST TRAIN",
"genre": "horror",
"desc": "The same train car, over and over. Study it. If anything is different, go back. If nothing changed, go forward. Get it right 8 times in a row to reach your stop.",
"controls": "→ / D go forward · ← / A go back",
"scoreLabel": "CARS",
"tasks": [
{
"stat": "score",
"target": 8,
"text": "Escape the Last Train"
}
],
"file": "games/2d/last-train.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/last-train.png"
},
{
"id": "static",
"n": 9,
"title": "STATIC",
"genre": "horror",
"desc": "An old TV at 3 AM. Somewhere in the channels a broadcast flashes four digits. Find all four and type the code. But channel 13 is not empty, and the face gets closer every time you land on it.",
"controls": "↑ / ↓ change channel · type digits 0-9 to enter the code · Backspace",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "score",
"target": 1,
"text": "Crack the code in Static"
}
],
"file": "games/2d/static.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/static.png"
},
{
"id": "the-basement",
"n": 10,
"title": "THE BASEMENT",
"genre": "horror",
"desc": "Keep the old generator running until morning. Feed it fuel, swap blown fuses, vent the pressure. When the lights die, something comes down the stairs.",
"controls": "Mouse: hold on the fuel can · click blown fuses · click the valve",
"scoreLabel": "SECONDS",
"tasks": [
{
"stat": "score",
"target": 120,
"text": "Keep the lights on 120s in The Basement"
}
],
"file": "games/2d/the-basement.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/the-basement.png"
},
{
"id": "phone-call",
"n": 11,
"title": "PHONE CALL",
"genre": "horror",
"desc": "You're home alone. The phone keeps ringing. Every answer tells the caller something. Never let him learn you're alone, and lock the house between calls.",
"controls": "Click an answer (or 1 / 2 / 3) · click doors & windows to lock them",
"scoreLabel": "CALLS",
"tasks": [
{
"stat": "score",
"target": 8,
"text": "Survive 8 calls in Phone Call"
}
],
"file": "games/2d/phone-call.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/phone-call.png"
},
{
"id": "hide",
"n": 12,
"title": "HIDE",
"genre": "horror",
"desc": "It's searching the house. Each round, pick a hiding place before it walks in. When it gets close, hold your breath and keep calm. It remembers where it found you before.",
"controls": "Click a hiding spot · hold SPACE to hold your breath, keep the marker in the green",
"scoreLabel": "ROUNDS",
"tasks": [
{
"stat": "score",
"target": 6,
"text": "Survive 6 rounds in Hide"
}
],
"file": "games/2d/hide.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/hide.png"
},
{
"id": "doll-house",
"n": 13,
"title": "DOLL HOUSE",
"genre": "horror",
"desc": "Seven dolls on the shelves. Every time you blink, one of them changes. Click the one that changed before the next blink, or it climbs one step closer.",
"controls": "Click the doll that changed",
"scoreLabel": "BLINKS",
"tasks": [
{
"stat": "score",
"target": 15,
"text": "Survive 15 blinks in Doll House"
}
],
"file": "games/2d/doll-house.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/doll-house.png"
},
{
"id": "sleep-paralysis",
"n": 14,
"title": "SLEEP PARALYSIS",
"genre": "horror",
"desc": "You wake up and can't move. Only your eyes and your breath. Keep your gaze on the figure so it can't come closer, and breathe in time with the circle to stay calm until dawn.",
"controls": "Mouse = where you look · tap SPACE when the circle is full to breathe",
"scoreLabel": "MINUTES",
"tasks": [
{
"stat": "score",
"target": 5,
"text": "Reach dawn in Sleep Paralysis"
}
],
"file": "games/2d/sleep-paralysis.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/sleep-paralysis.png"
},
{
"id": "night-drive",
"n": 15,
"title": "NIGHT DRIVE",
"genre": "horror",
"desc": "An empty highway at 3 AM. The same hitchhiker keeps appearing ahead. Don't slow down near him. Don't hit him. Watch your fuel and make it to town.",
"controls": "← / → steer · ↑ speed up · ↓ brake",
"scoreLabel": "KM",
"tasks": [
{
"stat": "score",
"target": 20,
"text": "Drive 20 km in Night Drive"
}
],
"file": "games/2d/night-drive.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/night-drive.png"
},
{
"id": "echo",
"n": 16,
"title": "ECHO",
"genre": "horror",
"desc": "You are blind. Clap and the sound shows you the walls for a moment. But the thing in the dark hunts by sound, and it heads to every clap you make.",
"controls": "WASD move · SPACE clap",
"scoreLabel": "ROOMS",
"tasks": [
{
"stat": "score",
"target": 3,
"text": "Find 3 exits in Echo"
}
],
"file": "games/2d/echo.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/echo.png"
},
{
"id": "pages",
"n": 17,
"title": "PAGES",
"genre": "horror",
"desc": "Eight torn pages are pinned to trees in a foggy wood. A tall faceless man appears between the trees, closer with every page. Looking at him fills your screen with static. Don't stare.",
"controls": "WASD move · mouse look · torch shows what you face",
"scoreLabel": "PAGES",
"tasks": [
{
"stat": "score",
"target": 8,
"text": "Collect all 8 pages"
}
],
"file": "games/2d/pages.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/pages.png"
},
{
"id": "the-elevator",
"n": 18,
"title": "THE ELEVATOR",
"genre": "horror",
"desc": "A note tells you how your floor looks. Ride the elevator, look out when the doors open, and only step out on the right floor. Step out on the wrong one and you're not coming back.",
"controls": "Click a floor button · ENTER/click STEP OUT · SPACE close doors",
"scoreLabel": "FLOORS",
"tasks": [
{
"stat": "score",
"target": 5,
"text": "Find 5 right floors in The Elevator"
}
],
"file": "games/2d/the-elevator.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/the-elevator.png"
},
{
"id": "radio-tower",
"n": 19,
"title": "RADIO TOWER",
"genre": "horror",
"desc": "After the blackout, you run the last radio tower. Tune the dial to find voices asking for help. Real survivors give real details. Mimics repeat themselves and get things wrong. Send the rescue truck only to real people.",
"controls": "← / → or mouse wheel tune · R rescue · X ignore",
"scoreLabel": "SAVED",
"tasks": [
{
"stat": "score",
"target": 6,
"text": "Save 6 survivors in Radio Tower"
}
],
"file": "games/2d/radio-tower.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/radio-tower.png"
},
{
"id": "mirror",
"n": 20,
"title": "MIRROR",
"genre": "horror",
"desc": "Your reflection copies every move, but it lives in a different room. Things hunt it on the other side of the glass. If your reflection dies, so do you. Grab the candles on both sides.",
"controls": "WASD / arrows move you AND your mirrored reflection",
"scoreLabel": "CANDLES",
"tasks": [
{
"stat": "score",
"target": 10,
"text": "Collect 10 candles in Mirror"
}
],
"file": "games/2d/mirror.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/mirror.png"
},
{
"id": "night-shift-store",
"n": 21,
"title": "NIGHT SHIFT STORE",
"genre": "horror",
"desc": "Ring up customers at a 24-hour store by typing each item's price code. Keep one eye on the CCTV. Something walks the aisles toward your counter. Hit the shutter before it reaches you.",
"controls": "Type the code shown · ENTER to scan · S / click SHUTTER",
"scoreLabel": "SALES",
"tasks": [
{
"stat": "score",
"target": 12,
"text": "Make 12 sales in Night Shift Store"
}
],
"file": "games/2d/night-shift-store.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/night-shift-store.png"
}
];
