// AUTO-GENERATED by tools/build_registry.py - do not edit by hand.
export const GAME_LIST = [
{
"id": "hell-maze",
"n": 1,
"title": "HELL MAZE",
"genre": "horror",
"desc": "Find the key, reach the exit. Something wakes up in the maze the moment you move, and it knows the way.",
"controls": "Arrow keys / WASD to move",
"scoreLabel": "MAZES",
"tasks": [
{
"stat": "score",
"target": 3,
"text": "Escape 3 mazes in Hell Maze"
}
],
"file": "games/2d/hell-maze.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/hell-maze.png"
},
{
"id": "the-house",
"n": 2,
"title": "THE HOUSE",
"genre": "horror",
"desc": "Find the 5 lost photos in a dark house and get out the front door. A ghost drifts through the walls. Hide in a wardrobe when it comes.",
"controls": "WASD / arrows move · E hide in a wardrobe",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "photos",
"target": 5,
"text": "Find all 5 photos in The House"
}
],
"file": "games/2d/the-house.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/the-house.png"
},
{
"id": "wrong-neighbour",
"n": 3,
"title": "WRONG NEIGHBOUR",
"genre": "horror",
"desc": "It's 2 AM. Someone knocks. Compare them with the residents book: one tiny difference means it isn't who it says it is. Open for real neighbours, never for the others.",
"controls": "O or click OPEN · K or click KEEP SHUT",
"scoreLabel": "VISITORS",
"tasks": [
{
"stat": "score",
"target": 10,
"text": "Judge 10 visitors right in Wrong Neighbour"
}
],
"file": "games/2d/wrong-neighbour.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/wrong-neighbour.png"
},
{
"id": "observation-ward",
"n": 4,
"title": "OBSERVATION WARD",
"genre": "horror",
"desc": "Watch four hospital rooms through the cameras from midnight to 6 AM. Things move, vanish or appear. Click whatever changed to report it. Four unreported anomalies and the ward is lost.",
"controls": "1-4 or arrows switch camera · click the thing that changed",
"scoreLabel": "REPORTS",
"tasks": [
{
"stat": "score",
"target": 12,
"text": "Report 12 anomalies in Observation Ward"
}
],
"file": "games/2d/observation-ward.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/observation-ward.png"
},
{
"id": "night-watch",
"n": 5,
"title": "NIGHT WATCH",
"genre": "horror",
"desc": "Night guard at an old toy factory. Three things walk the halls toward your office. Check the cameras, flash the door lights, slam the doors. The power won't last if you panic.",
"controls": "A / D close left / right door · Q / E door lights · SPACE cameras",
"scoreLabel": "HOURS",
"tasks": [
{
"stat": "score",
"target": 6,
"text": "Survive until 6 AM in Night Watch"
}
],
"file": "games/2d/night-watch.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/night-watch.png"
},
{
"id": "flashlight",
"n": 6,
"title": "FLASHLIGHT",
"genre": "horror",
"desc": "Lost in a black forest with one torch. Shadows crawl toward you from the dark and burn away in the beam, but the battery drains. Grab spare batteries and survive as long as you can.",
"controls": "WASD move · mouse aims the torch · right click / F toggles it",
"scoreLabel": "SECONDS",
"tasks": [
{
"stat": "score",
"target": 90,
"text": "Survive 90 seconds in Flashlight"
}
],
"file": "games/2d/flashlight.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/flashlight.png"
},
{
"id": "dont-look-back",
"n": 7,
"title": "DON'T LOOK BACK",
"genre": "horror",
"desc": "A statue follows you through the ruins. It only moves when you are not looking at it. Light all the candles while keeping it in sight.",
"controls": "WASD move · mouse = where you look",
"scoreLabel": "CANDLES",
"tasks": [
{
"stat": "score",
"target": 8,
"text": "Light 8 candles in Don't Look Back"
}
],
"file": "games/2d/dont-look-back.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/dont-look-back.png"
},
{
"id": "last-train",
"n": 8,
"title": "LAST TRAIN",
"genre": "horror",
"desc": "The same train car, over and over. Study it. If anything is different, go back. If nothing changed, go forward. Get it right 8 times in a row to reach your stop.",
"controls": "→ / D go forward · ← / A go back",
"scoreLabel": "CARS",
"tasks": [
{
"stat": "score",
"target": 8,
"text": "Escape the Last Train"
}
],
"file": "games/2d/last-train.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/last-train.png"
},
{
"id": "static",
"n": 9,
"title": "STATIC",
"genre": "horror",
"desc": "An old TV at 3 AM. Somewhere in the channels a broadcast flashes four digits. Find all four and type the code. But channel 13 is not empty, and the face gets closer every time you land on it.",
"controls": "↑ / ↓ change channel · type digits 0-9 to enter the code · Backspace",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "score",
"target": 1,
"text": "Crack the code in Static"
}
],
"file": "games/2d/static.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/static.png"
},
{
"id": "the-basement",
"n": 10,
"title": "THE BASEMENT",
"genre": "horror",
"desc": "Keep the old generator running until morning. Feed it fuel, swap blown fuses, vent the pressure. When the lights die, something comes down the stairs.",
"controls": "Mouse: hold on the fuel can · click blown fuses · click the valve",
"scoreLabel": "SECONDS",
"tasks": [
{
"stat": "score",
"target": 120,
"text": "Keep the lights on 120s in The Basement"
}
],
"file": "games/2d/the-basement.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/the-basement.png"
},
{
"id": "phone-call",
"n": 11,
"title": "PHONE CALL",
"genre": "horror",
"desc": "You're home alone. The phone keeps ringing. Every answer tells the caller something. Never let him learn you're alone, and lock the house between calls.",
"controls": "Click an answer (or 1 / 2 / 3) · click doors & windows to lock them",
"scoreLabel": "CALLS",
"tasks": [
{
"stat": "score",
"target": 8,
"text": "Survive 8 calls in Phone Call"
}
],
"file": "games/2d/phone-call.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/phone-call.png"
},
{
"id": "hide",
"n": 12,
"title": "HIDE",
"genre": "horror",
"desc": "It's searching the house. Each round, pick a hiding place before it walks in. When it gets close, hold your breath and keep calm. It remembers where it found you before.",
"controls": "Click a hiding spot · hold SPACE to hold your breath, keep the marker in the green",
"scoreLabel": "ROUNDS",
"tasks": [
{
"stat": "score",
"target": 6,
"text": "Survive 6 rounds in Hide"
}
],
"file": "games/2d/hide.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/hide.png"
},
{
"id": "doll-house",
"n": 13,
"title": "DOLL HOUSE",
"genre": "horror",
"desc": "Seven dolls on the shelves. Every time you blink, one of them changes. Click the one that changed before the next blink, or it climbs one step closer.",
"controls": "Click the doll that changed",
"scoreLabel": "BLINKS",
"tasks": [
{
"stat": "score",
"target": 15,
"text": "Survive 15 blinks in Doll House"
}
],
"file": "games/2d/doll-house.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/doll-house.png"
},
{
"id": "sleep-paralysis",
"n": 14,
"title": "SLEEP PARALYSIS",
"genre": "horror",
"desc": "You wake up and can't move. Only your eyes and your breath. Keep your gaze on the figure so it can't come closer, and breathe in time with the circle to stay calm until dawn.",
"controls": "Mouse = where you look · tap SPACE when the circle is full to breathe",
"scoreLabel": "MINUTES",
"tasks": [
{
"stat": "score",
"target": 5,
"text": "Reach dawn in Sleep Paralysis"
}
],
"file": "games/2d/sleep-paralysis.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/sleep-paralysis.png"
},
{
"id": "night-drive",
"n": 15,
"title": "NIGHT DRIVE",
"genre": "horror",
"desc": "An empty highway at 3 AM. The same hitchhiker keeps appearing ahead. Don't slow down near him. Don't hit him. Watch your fuel and make it to town.",
"controls": "← / → steer · ↑ speed up · ↓ brake",
"scoreLabel": "KM",
"tasks": [
{
"stat": "score",
"target": 20,
"text": "Drive 20 km in Night Drive"
}
],
"file": "games/2d/night-drive.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/night-drive.png"
},
{
"id": "echo",
"n": 16,
"title": "ECHO",
"genre": "horror",
"desc": "You are blind. Clap and the sound shows you the walls for a moment. But the thing in the dark hunts by sound, and it heads to every clap you make.",
"controls": "WASD move · SPACE clap",
"scoreLabel": "ROOMS",
"tasks": [
{
"stat": "score",
"target": 3,
"text": "Find 3 exits in Echo"
}
],
"file": "games/2d/echo.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/echo.png"
},
{
"id": "pages",
"n": 17,
"title": "PAGES",
"genre": "horror",
"desc": "Eight torn pages are pinned to trees in a foggy wood. A tall faceless man appears between the trees, closer with every page. Looking at him fills your screen with static. Don't stare.",
"controls": "WASD move · mouse look · torch shows what you face",
"scoreLabel": "PAGES",
"tasks": [
{
"stat": "score",
"target": 8,
"text": "Collect all 8 pages"
}
],
"file": "games/2d/pages.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/pages.png"
},
{
"id": "the-elevator",
"n": 18,
"title": "THE ELEVATOR",
"genre": "horror",
"desc": "A note tells you how your floor looks. Ride the elevator, look out when the doors open, and only step out on the right floor. Step out on the wrong one and you're not coming back.",
"controls": "Click a floor button · ENTER/click STEP OUT · SPACE close doors",
"scoreLabel": "FLOORS",
"tasks": [
{
"stat": "score",
"target": 5,
"text": "Find 5 right floors in The Elevator"
}
],
"file": "games/2d/the-elevator.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/the-elevator.png"
},
{
"id": "radio-tower",
"n": 19,
"title": "RADIO TOWER",
"genre": "horror",
"desc": "After the blackout, you run the last radio tower. Tune the dial to find voices asking for help. Real survivors give real details. Mimics repeat themselves and get things wrong. Send the rescue truck only to real people.",
"controls": "← / → or mouse wheel tune · R rescue · X ignore",
"scoreLabel": "SAVED",
"tasks": [
{
"stat": "score",
"target": 6,
"text": "Save 6 survivors in Radio Tower"
}
],
"file": "games/2d/radio-tower.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/radio-tower.png"
},
{
"id": "mirror",
"n": 20,
"title": "MIRROR",
"genre": "horror",
"desc": "Your reflection copies every move, but it lives in a different room. Things hunt it on the other side of the glass. If your reflection dies, so do you. Grab the candles on both sides.",
"controls": "WASD / arrows move you AND your mirrored reflection",
"scoreLabel": "CANDLES",
"tasks": [
{
"stat": "score",
"target": 10,
"text": "Collect 10 candles in Mirror"
}
],
"file": "games/2d/mirror.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/mirror.png"
},
{
"id": "night-shift-store",
"n": 21,
"title": "NIGHT SHIFT STORE",
"genre": "horror",
"desc": "Ring up customers at a 24-hour store by typing each item's price code. Keep one eye on the CCTV. Something walks the aisles toward your counter. Hit the shutter before it reaches you.",
"controls": "Type the code shown · ENTER to scan · S / click SHUTTER",
"scoreLabel": "SALES",
"tasks": [
{
"stat": "score",
"target": 12,
"text": "Make 12 sales in Night Shift Store"
}
],
"file": "games/2d/night-shift-store.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/night-shift-store.png"
},
{
"id": "breakout",
"n": 1,
"title": "BREAKOUT",
"genre": "fun",
"desc": "Smash every neon brick. Tough bricks take two hits, glowing ones drop power-ups: wide paddle, multiball, slow ball. Each wall comes back thicker.",
"controls": "Mouse / touch or ← → to move · Space / click to launch",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "score",
"target": 1500,
"text": "Score 1500 in Breakout"
},
{
"stat": "walls",
"target": 2,
"text": "Clear 2 walls in Breakout"
}
],
"file": "games/2d/breakout.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/breakout.png"
},
{
"id": "pong-duel",
"n": 1,
"title": "PONG DUEL",
"genre": "fun",
"modes": [
"online",
"local"
],
"minPlayers": 2,
"maxPlayers": 2,
"desc": "Neon pong against a real person: online with a friend, or two players on one keyboard. Edge hits curve the ball, and every 5 hits it speeds up. First to 7.",
"controls": "Online: mouse / touch or ↑ ↓ · Same screen: left W S, right ↑ ↓",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "won",
"target": 1,
"text": "Win a Pong Duel"
}
],
"file": "games/2d/pong-duel.html",
"dim": "2d"
},
{
"id": "flappy",
"n": 2,
"title": "FLAPPY",
"genre": "fun",
"desc": "Tap to flap through the neon pipes. Gaps shrink, pipes start to slide, and every 10 points the city changes colour.",
"controls": "Space / click / tap to flap",
"scoreLabel": "PIPES",
"tasks": [
{
"stat": "score",
"target": 15,
"text": "Fly through 15 pipes in Flappy"
}
],
"file": "games/2d/flappy.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/flappy.png"
},
{
"id": "pixel-miner",
"n": 3,
"title": "PIXEL MINER",
"genre": "fun",
"desc": "Drill down, fill your cargo with copper, silver, gold and gems, then fly back up to sell before the fuel runs out. Upgrade the drill, tank and cargo bay to go deeper. Watch out for lava.",
"controls": "← → ↓ to drill · hold ↑ to fly up · at the surface: 1 drill, 2 tank, 3 cargo upgrades",
"scoreLabel": "CASH EARNED",
"tasks": [
{
"stat": "score",
"target": 600,
"text": "Earn 600 cash in Pixel Miner"
},
{
"stat": "depth",
"target": 60,
"text": "Reach 60 m deep in Pixel Miner"
}
],
"file": "games/2d/pixel-miner.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/pixel-miner.png"
},
{
"id": "neon-runner",
"n": 4,
"title": "NEON RUNNER",
"genre": "fun",
"desc": "Run the rooftops of a neon city. Jump the barriers, slide under the lasers, double-jump the gaps and grab the coins. It never stops getting faster.",
"controls": "Space / ↑ / tap = jump (twice = double jump) · ↓ / S = slide",
"scoreLabel": "METRES",
"tasks": [
{
"stat": "score",
"target": 800,
"text": "Run 800 m in Neon Runner"
},
{
"stat": "coins",
"target": 40,
"text": "Grab 40 coins in one Neon Runner run"
}
],
"file": "games/2d/neon-runner.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/neon-runner.png"
},
{
"id": "neon-pong",
"n": 5,
"title": "NEON PONG",
"genre": "fun",
"desc": "Classic pong against a CPU that gets smarter every rally. Hit the ball with the edge of your paddle to curve it. First to 7.",
"controls": "Mouse / touch or ↑ ↓ (W S) to move",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "score",
"target": 7,
"text": "Win a match of Neon Pong"
},
{
"stat": "rally",
"target": 12,
"text": "Make a 12-hit rally in Neon Pong"
}
],
"file": "games/2d/neon-pong.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/neon-pong.png"
},
{
"id": "neon-snake",
"n": 6,
"title": "NEON SNAKE",
"genre": "fun",
"desc": "Eat, grow, don't bite yourself. Gold fruit is worth 5 but vanishes fast, and every 10 fruit a wall block appears.",
"controls": "Arrow keys / WASD or swipe",
"scoreLabel": "FRUIT",
"tasks": [
{
"stat": "score",
"target": 25,
"text": "Eat 25 fruit in Neon Snake"
}
],
"file": "games/2d/neon-snake.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/neon-snake.png"
},
{
"id": "2048",
"n": 1,
"title": "2048",
"genre": "mind",
"desc": "Slide the tiles, merge equal numbers, reach 2048. Keep going after that for a bigger score. One undo per game.",
"controls": "Arrow keys / WASD or swipe · U = undo once",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "score",
"target": 3000,
"text": "Score 3000 in 2048"
},
{
"stat": "tile",
"target": 512,
"text": "Make a 512 tile in 2048"
}
],
"file": "games/2d/2048.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/2048.png"
},
{
"id": "atlas",
"n": 2,
"title": "ATLAS",
"genre": "mind",
"desc": "The classic place-name chain against the CPU. Name a country that starts with the last letter of the one before. No repeats. 15 seconds a turn, and the CPU knows its geography.",
"controls": "Type (or tap the keyboard) · Enter to answer",
"scoreLabel": "COUNTRIES",
"tasks": [
{
"stat": "score",
"target": 8,
"text": "Name 8 countries in one Atlas game"
}
],
"file": "games/2d/atlas.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/atlas.png"
},
{
"id": "chess",
"n": 3,
"title": "CHESS",
"genre": "mind",
"desc": "Full chess against the CPU: castling, en passant, promotion, check and mate. Pick EASY, MEDIUM or HARD. Beating HARD is worth the most.",
"controls": "Click / tap a piece, then a highlighted square",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "won",
"target": 1,
"text": "Beat the CPU at Chess"
}
],
"file": "games/2d/chess.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/chess.png"
},
{
"id": "tic-tac-toe",
"n": 4,
"title": "TIC TAC TOE",
"genre": "mind",
"desc": "Best of 9 rounds against the CPU. It starts sloppy and gets sharper every round you win. Can you beat the perfect player at the end?",
"controls": "Click / tap a square (or 1-9 on the number pad layout)",
"scoreLabel": "WINS",
"tasks": [
{
"stat": "score",
"target": 3,
"text": "Win 3 rounds of Tic Tac Toe in one match"
}
],
"file": "games/2d/tic-tac-toe.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/tic-tac-toe.png"
},
{
"id": "wordle",
"n": 5,
"title": "WORDLE",
"genre": "mind",
"desc": "Guess the 5-letter word in 6 tries. Green = right letter, right spot. Yellow = in the word, wrong spot. Grey = not in the word. Solve as many words in a row as you can.",
"controls": "Type or tap the keyboard · Enter to guess",
"scoreLabel": "WORDS",
"tasks": [
{
"stat": "score",
"target": 3,
"text": "Solve 3 words in a row in Wordle"
}
],
"file": "games/2d/wordle.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/wordle.png"
},
{
"id": "aim-trainer",
"n": 6,
"title": "AIM TRAINER",
"genre": "mind",
"desc": "30 seconds. Targets shrink while they live, some drift, gold ones are worth triple. Misses cost points, so don't spray.",
"controls": "Click / tap the targets",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "score",
"target": 40,
"text": "Score 40 in Aim Trainer"
},
{
"stat": "accuracy",
"target": 90,
"text": "Get 90% accuracy in Aim Trainer"
}
],
"file": "games/2d/aim-trainer.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/aim-trainer.png"
},
{
"id": "reaction-test",
"n": 7,
"title": "REACTION TEST",
"genre": "mind",
"desc": "Wait for green, then hit as fast as you can. Five tries, your average counts. Click on red and that try is a fail. Fake-out colours show up from try 3.",
"controls": "Click / tap / Space when the screen turns GREEN",
"scoreLabel": "MS AVG",
"lowerIsBetter": true,
"tasks": [
{
"stat": "best",
"target": 1,
"text": "Finish a Reaction Test with no early clicks"
}
],
"file": "games/2d/reaction-test.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/reaction-test.png"
},
{
"id": "colour-quiz",
"n": 8,
"title": "COLOUR QUIZ",
"genre": "mind",
"desc": "One tile is a slightly different shade. Find it before the timer runs out. The grid grows and the difference shrinks every round.",
"controls": "Click / tap the odd tile",
"scoreLabel": "ROUNDS",
"tasks": [
{
"stat": "score",
"target": 15,
"text": "Reach round 15 in Colour Quiz"
}
],
"file": "games/2d/colour-quiz.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/colour-quiz.png"
},
{
"id": "sequence-memory",
"n": 9,
"title": "SEQUENCE MEMORY",
"genre": "mind",
"desc": "Squares light up one after another with a note each. Repeat the order. One more step every round, and it plays faster as you go.",
"controls": "Click / tap the squares (or keys 1-9)",
"scoreLabel": "STEPS",
"tasks": [
{
"stat": "score",
"target": 10,
"text": "Remember 10 steps in Sequence Memory"
}
],
"file": "games/2d/sequence-memory.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/sequence-memory.png"
},
{
"id": "typing-speed",
"n": 10,
"title": "TYPING SPEED",
"genre": "mind",
"desc": "60 seconds, real words. Your words-per-minute counts only correct words, so speed without accuracy gets you nowhere.",
"controls": "Type the highlighted word · Space moves to the next word",
"scoreLabel": "WPM",
"tasks": [
{
"stat": "score",
"target": 35,
"text": "Type 35 WPM in Typing Speed"
}
],
"file": "games/2d/typing-speed.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/typing-speed.png"
},
{
"id": "match-3",
"n": 1,
"title": "MATCH-3",
"genre": "relax",
"desc": "Swap neighbouring gems to line up three or more. Four in a row makes a line-blaster, five makes a colour bomb. 30 calm moves, no timer.",
"controls": "Click a gem then a neighbour, or drag / swipe",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "score",
"target": 3000,
"text": "Score 3000 in Match-3"
}
],
"file": "games/2d/match-3.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/match-3.png"
},
{
"id": "word-connect",
"n": 2,
"title": "WORD CONNECT",
"genre": "relax",
"desc": "Swipe across the letter wheel to spell words and fill every slot. Extra real words count as bonus words. Ten calm levels, no timer.",
"controls": "Drag across the letters (or type + Enter) · Shuffle button mixes the wheel",
"scoreLabel": "WORDS",
"tasks": [
{
"stat": "score",
"target": 20,
"text": "Find 20 words in Word Connect"
}
],
"file": "games/2d/word-connect.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/word-connect.png"
},
{
"id": "mystery-cafe",
"n": 3,
"title": "MYSTERY CAFÉ",
"genre": "relax",
"desc": "Run a cozy café for three days. Read what each guest wants and serve the right drink. Something goes missing every day, and the guests let slip clues. Close up and name who did it.",
"controls": "Click / tap a drink to serve it · pick the culprit at closing time",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "solved",
"target": 2,
"text": "Solve 2 café mysteries in one game"
}
],
"file": "games/2d/mystery-cafe.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/mystery-cafe.png"
},
{
"id": "battleship",
"n": 4,
"title": "BATTLESHIP",
"genre": "relax",
"desc": "Sink the CPU fleet before it sinks yours. Your ships are placed for you (R to shuffle before the first shot). The CPU hunts smartly once it finds you.",
"controls": "Click / tap the enemy sea to fire · R = shuffle your fleet before you start",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "won",
"target": 1,
"text": "Win a game of Battleship"
}
],
"file": "games/2d/battleship.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/battleship.png"
}
];
