// AUTO-GENERATED by tools/build_registry.py - do not edit by hand.
export const GAME_LIST = [
{
"id": "hell-maze",
"n": 1,
"title": "HELL MAZE",
"genre": "horror",
"desc": "Find the key, reach the exit. Something wakes up in the maze the moment you move, and it knows the way.",
"controls": "Arrow keys / WASD to move",
"scoreLabel": "MAZES",
"tasks": [
{
"stat": "score",
"target": 3,
"text": "Escape 3 mazes in Hell Maze"
}
],
"file": "games/2d/hell-maze.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/hell-maze.png"
},
{
"id": "the-house",
"n": 2,
"title": "THE HOUSE",
"genre": "horror",
"desc": "Find the 5 lost photos in a dark house and get out the front door. A ghost drifts through the walls. Hide in a wardrobe when it comes.",
"controls": "WASD / arrows move · E hide in a wardrobe",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "photos",
"target": 5,
"text": "Find all 5 photos in The House"
}
],
"file": "games/2d/the-house.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/the-house.png"
},
{
"id": "wrong-neighbour",
"n": 3,
"title": "WRONG NEIGHBOUR",
"genre": "horror",
"desc": "It's 2 AM. Someone knocks. Compare them with the residents book: one tiny difference means it isn't who it says it is. Open for real neighbours, never for the others.",
"controls": "O or click OPEN · K or click KEEP SHUT",
"scoreLabel": "VISITORS",
"tasks": [
{
"stat": "score",
"target": 10,
"text": "Judge 10 visitors right in Wrong Neighbour"
}
],
"file": "games/2d/wrong-neighbour.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/wrong-neighbour.png"
},
{
"id": "observation-ward",
"n": 4,
"title": "OBSERVATION WARD",
"genre": "horror",
"desc": "Watch four hospital rooms through the cameras from midnight to 6 AM. Things move, vanish or appear. Click whatever changed to report it. Four unreported anomalies and the ward is lost.",
"controls": "1-4 or arrows switch camera · click the thing that changed",
"scoreLabel": "REPORTS",
"tasks": [
{
"stat": "score",
"target": 12,
"text": "Report 12 anomalies in Observation Ward"
}
],
"file": "games/2d/observation-ward.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/observation-ward.png"
},
{
"id": "night-watch",
"n": 5,
"title": "NIGHT WATCH",
"genre": "horror",
"desc": "Night guard at an old toy factory. Three things walk the halls toward your office. Check the cameras, flash the door lights, slam the doors. The power won't last if you panic.",
"controls": "A / D close left / right door · Q / E door lights · SPACE cameras",
"scoreLabel": "HOURS",
"tasks": [
{
"stat": "score",
"target": 6,
"text": "Survive until 6 AM in Night Watch"
}
],
"file": "games/2d/night-watch.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/night-watch.png"
},
{
"id": "flashlight",
"n": 6,
"title": "FLASHLIGHT",
"genre": "horror",
"desc": "Lost in a black forest with one torch. Shadows crawl toward you from the dark and burn away in the beam, but the battery drains. Grab spare batteries and survive as long as you can.",
"controls": "WASD move · mouse aims the torch · right click / F toggles it",
"scoreLabel": "SECONDS",
"tasks": [
{
"stat": "score",
"target": 90,
"text": "Survive 90 seconds in Flashlight"
}
],
"file": "games/2d/flashlight.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/flashlight.png"
},
{
"id": "dont-look-back",
"n": 7,
"title": "DON'T LOOK BACK",
"genre": "horror",
"desc": "A statue follows you through the ruins. It only moves when you are not looking at it. Light all the candles while keeping it in sight.",
"controls": "WASD move · mouse = where you look",
"scoreLabel": "CANDLES",
"tasks": [
{
"stat": "score",
"target": 8,
"text": "Light 8 candles in Don't Look Back"
}
],
"file": "games/2d/dont-look-back.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/dont-look-back.png"
},
{
"id": "last-train",
"n": 8,
"title": "LAST TRAIN",
"genre": "horror",
"desc": "The same train car, over and over. Study it. If anything is different, go back. If nothing changed, go forward. Get it right 8 times in a row to reach your stop.",
"controls": "→ / D go forward · ← / A go back",
"scoreLabel": "CARS",
"tasks": [
{
"stat": "score",
"target": 8,
"text": "Escape the Last Train"
}
],
"file": "games/2d/last-train.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/last-train.png"
},
{
"id": "static",
"n": 9,
"title": "STATIC",
"genre": "horror",
"desc": "An old TV at 3 AM. Somewhere in the channels a broadcast flashes four digits. Find all four and type the code. But channel 13 is not empty, and the face gets closer every time you land on it.",
"controls": "↑ / ↓ change channel · type digits 0-9 to enter the code · Backspace",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "score",
"target": 1,
"text": "Crack the code in Static"
}
],
"file": "games/2d/static.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/static.png"
},
{
"id": "the-basement",
"n": 10,
"title": "THE BASEMENT",
"genre": "horror",
"desc": "Keep the old generator running until morning. Feed it fuel, swap blown fuses, vent the pressure. When the lights die, something comes down the stairs.",
"controls": "Mouse: hold on the fuel can · click blown fuses · click the valve",
"scoreLabel": "SECONDS",
"tasks": [
{
"stat": "score",
"target": 120,
"text": "Keep the lights on 120s in The Basement"
}
],
"file": "games/2d/the-basement.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/the-basement.png"
},
{
"id": "phone-call",
"n": 11,
"title": "PHONE CALL",
"genre": "horror",
"desc": "You're home alone. The phone keeps ringing. Every answer tells the caller something. Never let him learn you're alone, and lock the house between calls.",
"controls": "Click an answer (or 1 / 2 / 3) · click doors & windows to lock them",
"scoreLabel": "CALLS",
"tasks": [
{
"stat": "score",
"target": 8,
"text": "Survive 8 calls in Phone Call"
}
],
"file": "games/2d/phone-call.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/phone-call.png"
},
{
"id": "hide",
"n": 12,
"title": "HIDE",
"genre": "horror",
"desc": "It's searching the house. Each round, pick a hiding place before it walks in. When it gets close, hold your breath and keep calm. It remembers where it found you before.",
"controls": "Click a hiding spot · hold SPACE to hold your breath, keep the marker in the green",
"scoreLabel": "ROUNDS",
"tasks": [
{
"stat": "score",
"target": 6,
"text": "Survive 6 rounds in Hide"
}
],
"file": "games/2d/hide.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/hide.png"
},
{
"id": "doll-house",
"n": 13,
"title": "DOLL HOUSE",
"genre": "horror",
"desc": "Seven dolls on the shelves. Every time you blink, one of them changes. Click the one that changed before the next blink, or it climbs one step closer.",
"controls": "Click the doll that changed",
"scoreLabel": "BLINKS",
"tasks": [
{
"stat": "score",
"target": 15,
"text": "Survive 15 blinks in Doll House"
}
],
"file": "games/2d/doll-house.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/doll-house.png"
},
{
"id": "sleep-paralysis",
"n": 14,
"title": "SLEEP PARALYSIS",
"genre": "horror",
"desc": "You wake up and can't move. Only your eyes and your breath. Keep your gaze on the figure so it can't come closer, and breathe in time with the circle to stay calm until dawn.",
"controls": "Mouse = where you look · tap SPACE when the circle is full to breathe",
"scoreLabel": "MINUTES",
"tasks": [
{
"stat": "score",
"target": 5,
"text": "Reach dawn in Sleep Paralysis"
}
],
"file": "games/2d/sleep-paralysis.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/sleep-paralysis.png"
},
{
"id": "night-drive",
"n": 15,
"title": "NIGHT DRIVE",
"genre": "horror",
"desc": "An empty highway at 3 AM. The same hitchhiker keeps appearing ahead. Don't slow down near him. Don't hit him. Watch your fuel and make it to town.",
"controls": "← / → steer · ↑ speed up · ↓ brake",
"scoreLabel": "KM",
"tasks": [
{
"stat": "score",
"target": 20,
"text": "Drive 20 km in Night Drive"
}
],
"file": "games/2d/night-drive.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/night-drive.png"
},
{
"id": "echo",
"n": 16,
"title": "ECHO",
"genre": "horror",
"desc": "You are blind. Clap and the sound shows you the walls for a moment. But the thing in the dark hunts by sound, and it heads to every clap you make.",
"controls": "WASD move · SPACE clap",
"scoreLabel": "ROOMS",
"tasks": [
{
"stat": "score",
"target": 3,
"text": "Find 3 exits in Echo"
}
],
"file": "games/2d/echo.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/echo.png"
},
{
"id": "pages",
"n": 17,
"title": "PAGES",
"genre": "horror",
"desc": "Eight torn pages are pinned to trees in a foggy wood. A tall faceless man appears between the trees, closer with every page. Looking at him fills your screen with static. Don't stare.",
"controls": "WASD move · mouse look · torch shows what you face",
"scoreLabel": "PAGES",
"tasks": [
{
"stat": "score",
"target": 8,
"text": "Collect all 8 pages"
}
],
"file": "games/2d/pages.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/pages.png"
},
{
"id": "the-elevator",
"n": 18,
"title": "THE ELEVATOR",
"genre": "horror",
"desc": "A note tells you how your floor looks. Ride the elevator, look out when the doors open, and only step out on the right floor. Step out on the wrong one and you're not coming back.",
"controls": "Click a floor button · ENTER/click STEP OUT · SPACE close doors",
"scoreLabel": "FLOORS",
"tasks": [
{
"stat": "score",
"target": 5,
"text": "Find 5 right floors in The Elevator"
}
],
"file": "games/2d/the-elevator.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/the-elevator.png"
},
{
"id": "radio-tower",
"n": 19,
"title": "RADIO TOWER",
"genre": "horror",
"desc": "After the blackout, you run the last radio tower. Tune the dial to find voices asking for help. Real survivors give real details. Mimics repeat themselves and get things wrong. Send the rescue truck only to real people.",
"controls": "← / → or mouse wheel tune · R rescue · X ignore",
"scoreLabel": "SAVED",
"tasks": [
{
"stat": "score",
"target": 6,
"text": "Save 6 survivors in Radio Tower"
}
],
"file": "games/2d/radio-tower.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/radio-tower.png"
},
{
"id": "mirror",
"n": 20,
"title": "MIRROR",
"genre": "horror",
"desc": "Your reflection copies every move, but it lives in a different room. Things hunt it on the other side of the glass. If your reflection dies, so do you. Grab the candles on both sides.",
"controls": "WASD / arrows move you AND your mirrored reflection",
"scoreLabel": "CANDLES",
"tasks": [
{
"stat": "score",
"target": 10,
"text": "Collect 10 candles in Mirror"
}
],
"file": "games/2d/mirror.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/mirror.png"
},
{
"id": "night-shift-store",
"n": 21,
"title": "NIGHT SHIFT STORE",
"genre": "horror",
"desc": "Ring up customers at a 24-hour store by typing each item's price code. Keep one eye on the CCTV. Something walks the aisles toward your counter. Hit the shutter before it reaches you.",
"controls": "Type the code shown · ENTER to scan · S / click SHUTTER",
"scoreLabel": "SALES",
"tasks": [
{
"stat": "score",
"target": 12,
"text": "Make 12 sales in Night Shift Store"
}
],
"file": "games/2d/night-shift-store.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/night-shift-store.png"
},
{
"id": "the-well",
"n": 22,
"title": "THE WELL",
"genre": "horror",
"desc": "An old well behind the farmhouse. Lower the bucket and see what comes up. The deeper you go, the stranger it gets. If the rope suddenly goes tight, LET GO, or whatever is down there pulls you in.",
"controls": "Hold Space / mouse to lower the bucket, release to pull it up · tap fast when the rope jerks",
"scoreLabel": "FINDS",
"tasks": [
{
"stat": "score",
"target": 8,
"text": "Pull up 8 things from The Well"
}
],
"file": "games/2d/the-well.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/the-well.png"
},
{
"id": "candle",
"n": 23,
"title": "CANDLE",
"genre": "horror",
"desc": "The power is out. Your candle is burning down and the light shrinks with it. Find the spare candles hidden around the dark house and light them before yours dies. Things in the dark only move when your light is small.",
"controls": "Arrow keys / WASD to walk · E (or tap) next to a candle to light it",
"scoreLabel": "SECONDS",
"tasks": [
{
"stat": "score",
"target": 90,
"text": "Keep the light for 90 seconds in Candle"
}
],
"file": "games/2d/candle.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/candle.png"
},
{
"id": "knock-knock",
"n": 24,
"title": "KNOCK KNOCK",
"genre": "horror",
"desc": "Your family has a secret knock. Memorise it, because tonight people keep knocking. Same knock: open the door, it's family. Any other knock: keep it shut. Things outside are learning the rhythm.",
"controls": "Listen · O = open · K = keep shut (or tap the buttons) · R replays the secret knock (twice per game)",
"scoreLabel": "NIGHT VISITORS",
"tasks": [
{
"stat": "score",
"target": 8,
"text": "Answer 8 knocks right in Knock Knock"
}
],
"file": "games/2d/knock-knock.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/knock-knock.png"
},
{
"id": "the-attic",
"n": 25,
"title": "THE ATTIC",
"genre": "horror",
"desc": "Something scratches above your bedroom every night. Climb into the attic with a torch and find what is making the noise. Follow the sound (headphones help, the rings show it too) and open the right box. Open the wrong ones and you wake it up.",
"controls": "Mouse / touch aims the torch · arrow keys / WASD walk · click a box (or E nearby) to open it",
"scoreLabel": "NIGHTS",
"tasks": [
{
"stat": "score",
"target": 3,
"text": "Survive 3 nights in The Attic"
}
],
"file": "games/2d/the-attic.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/the-attic.png"
},
{
"id": "fog-road",
"n": 28,
"title": "FOG ROAD",
"genre": "horror",
"desc": "Walk the old road home through fog so thick you can see three metres. Something follows you. When its footsteps get close, stop and turn around: it hates being looked at. Keep to the road, reach the town lights.",
"controls": "Hold ↑ / W (or hold the screen) to walk · Space / tap = turn around and look · ← → stay on the road",
"scoreLabel": "METRES",
"tasks": [
{
"stat": "score",
"target": 600,
"text": "Walk 600 m down the Fog Road"
}
],
"file": "games/2d/fog-road.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/fog-road.png"
},
{
"id": "blink",
"n": 35,
"title": "BLINK",
"genre": "horror",
"desc": "The statues only move when you can't see them. Your eyes dry out and you WILL blink, so blink on purpose when it's safe. Cross each gallery to the door before they reach you.",
"controls": "Arrow keys / WASD to move · hold B (or the eye button) to blink on purpose",
"scoreLabel": "GALLERIES",
"tasks": [
{
"stat": "score",
"target": 4,
"text": "Cross 4 galleries in Blink"
}
],
"file": "games/2d/blink.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/blink.png"
},
{
"id": "breakout",
"n": 1,
"title": "BREAKOUT",
"genre": "fun",
"desc": "Smash every neon brick. Tough bricks take two hits, glowing ones drop power-ups: wide paddle, multiball, slow ball. Each wall comes back thicker.",
"controls": "Mouse / touch or ← → to move · Space / click to launch",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "score",
"target": 1500,
"text": "Score 1500 in Breakout"
},
{
"stat": "walls",
"target": 2,
"text": "Clear 2 walls in Breakout"
}
],
"file": "games/2d/breakout.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/breakout.png"
},
{
"id": "pong-duel",
"n": 1,
"title": "PONG DUEL",
"genre": "fun",
"modes": [
"online",
"local"
],
"minPlayers": 2,
"maxPlayers": 2,
"desc": "Neon pong against a real person: online with a friend, or two players on one keyboard. Edge hits curve the ball, and every 5 hits it speeds up. First to 7.",
"controls": "Online: mouse / touch or ↑ ↓ · Same screen: left W S, right ↑ ↓",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "won",
"target": 1,
"text": "Win a Pong Duel"
}
],
"file": "games/2d/pong-duel.html",
"dim": "2d",
"cover": "games/covers/pong-duel.png"
},
{
"id": "flappy",
"n": 2,
"title": "FLAPPY",
"genre": "fun",
"desc": "Tap to flap through the neon pipes. Gaps shrink, pipes start to slide, and every 10 points the city changes colour.",
"controls": "Space / click / tap to flap",
"scoreLabel": "PIPES",
"tasks": [
{
"stat": "score",
"target": 15,
"text": "Fly through 15 pipes in Flappy"
}
],
"file": "games/2d/flappy.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/flappy.png"
},
{
"id": "pixel-miner",
"n": 3,
"title": "PIXEL MINER",
"genre": "fun",
"desc": "Drill down, fill your cargo with copper, silver, gold and gems, then fly back up to sell before the fuel runs out. Upgrade the drill, tank and cargo bay to go deeper. Watch out for lava.",
"controls": "← → ↓ to drill · hold ↑ to fly up · at the surface: 1 drill, 2 tank, 3 cargo upgrades",
"scoreLabel": "CASH EARNED",
"tasks": [
{
"stat": "score",
"target": 600,
"text": "Earn 600 cash in Pixel Miner"
},
{
"stat": "depth",
"target": 60,
"text": "Reach 60 m deep in Pixel Miner"
}
],
"file": "games/2d/pixel-miner.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/pixel-miner.png"
},
{
"id": "neon-runner",
"n": 4,
"title": "NEON RUNNER",
"genre": "fun",
"desc": "Run the rooftops of a neon city. Jump the barriers, slide under the lasers, double-jump the gaps and grab the coins. It never stops getting faster.",
"controls": "Space / ↑ / tap = jump (twice = double jump) · ↓ / S = slide",
"scoreLabel": "METRES",
"tasks": [
{
"stat": "score",
"target": 800,
"text": "Run 800 m in Neon Runner"
},
{
"stat": "coins",
"target": 40,
"text": "Grab 40 coins in one Neon Runner run"
}
],
"file": "games/2d/neon-runner.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/neon-runner.png"
},
{
"id": "neon-pong",
"n": 5,
"title": "NEON PONG",
"genre": "fun",
"desc": "Classic pong against a CPU that gets smarter every rally. Hit the ball with the edge of your paddle to curve it. First to 7.",
"controls": "Mouse / touch or ↑ ↓ (W S) to move",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "score",
"target": 7,
"text": "Win a match of Neon Pong"
},
{
"stat": "rally",
"target": 12,
"text": "Make a 12-hit rally in Neon Pong"
}
],
"file": "games/2d/neon-pong.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/neon-pong.png"
},
{
"id": "neon-snake",
"n": 6,
"title": "NEON SNAKE",
"genre": "fun",
"desc": "Eat, grow, don't bite yourself. Gold fruit is worth 5 but vanishes fast, and every 10 fruit a wall block appears.",
"controls": "Arrow keys / WASD or swipe",
"scoreLabel": "FRUIT",
"tasks": [
{
"stat": "score",
"target": 25,
"text": "Eat 25 fruit in Neon Snake"
}
],
"file": "games/2d/neon-snake.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/neon-snake.png"
},
{
"id": "asteroids",
"n": 7,
"title": "ASTEROIDS",
"genre": "fun",
"desc": "Spin, thrust and blast the rocks into smaller rocks. The screen wraps around. A saucer drops in now and then: shoot it for a shield.",
"controls": "← → rotate · ↑ thrust · Space fire · Shift hyperspace",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "score",
"target": 3000,
"text": "Score 3000 in Asteroids"
}
],
"file": "games/2d/asteroids.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/asteroids.png"
},
{
"id": "space-invaders",
"n": 8,
"title": "SPACE INVADERS",
"genre": "fun",
"desc": "Rows of invaders march down, faster as their numbers drop. Hide behind the crumbling bunkers, shoot the mystery ship for bonus points, and don't let them land.",
"controls": "← → move · Space fire",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "score",
"target": 2000,
"text": "Score 2000 in Space Invaders"
},
{
"stat": "waves",
"target": 2,
"text": "Clear 2 waves in Space Invaders"
}
],
"file": "games/2d/space-invaders.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/space-invaders.png"
},
{
"id": "doodle-jump",
"n": 9,
"title": "DOODLE JUMP",
"genre": "fun",
"desc": "Bounce up an endless tower of platforms. Some break, some slide, springs launch you sky-high and jetpacks blast you even higher. Wrap around the sides. Don't fall.",
"controls": "← → / A D or tilt with the mouse / touch",
"scoreLabel": "HEIGHT",
"tasks": [
{
"stat": "score",
"target": 2500,
"text": "Reach 2500 height in Doodle Jump"
}
],
"file": "games/2d/doodle-jump.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/doodle-jump.png"
},
{
"id": "fruit-slice",
"n": 11,
"title": "FRUIT SLICE",
"genre": "fun",
"desc": "Fruit flies up, you swipe through it. Slice several in one swipe for combo points. Miss three fruits and it's over; slice a bomb and it's over right away.",
"controls": "Drag / swipe through the fruit",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "score",
"target": 150,
"text": "Score 150 in Fruit Slice"
},
{
"stat": "combo",
"target": 4,
"text": "Slice 4 fruit in one swipe in Fruit Slice"
}
],
"file": "games/2d/fruit-slice.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/fruit-slice.png"
},
{
"id": "tower-stack",
"n": 12,
"title": "TOWER STACK",
"genre": "fun",
"desc": "A block slides back and forth. Drop it on the tower: whatever hangs over the edge gets sliced off. Land it perfectly to keep it full size, and five perfects in a row grow it back.",
"controls": "Space / click / tap to drop",
"scoreLabel": "FLOORS",
"tasks": [
{
"stat": "score",
"target": 25,
"text": "Stack 25 floors in Tower Stack"
}
],
"file": "games/2d/tower-stack.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/tower-stack.png"
},
{
"id": "helicopter-cave",
"n": 13,
"title": "HELICOPTER CAVE",
"genre": "fun",
"desc": "Hold to rise, let go to fall. The cave twists and narrows, pillars pop up in the middle, and fuel cans give bonus points. How far can you fly?",
"controls": "Hold Space / mouse / touch to go up",
"scoreLabel": "METRES",
"tasks": [
{
"stat": "score",
"target": 700,
"text": "Fly 700 m in Helicopter Cave"
}
],
"file": "games/2d/helicopter-cave.html",
"dim": "2d",
"modes": [
"sp"
]
},
{
"id": "whack-a-mole",
"n": 14,
"title": "WHACK-A-MOLE",
"genre": "fun",
"desc": "45 seconds of bonking. Moles pop up faster and faster. Golden moles are worth 5, helmet moles need two hits, and never ever hit the bunny.",
"controls": "Click / tap the moles (or keys 1-9 on the number pad layout)",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "score",
"target": 60,
"text": "Score 60 in Whack-a-Mole"
}
],
"file": "games/2d/whack-a-mole.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/whack-a-mole.png"
},
{
"id": "dino-run",
"n": 19,
"title": "DINO RUN",
"genre": "fun",
"desc": "The little offline dino, on neon. Jump the cacti, duck the pterodactyls, and survive the night when the colours flip. The speed never stops climbing.",
"controls": "Space / ↑ / tap = jump · ↓ = duck",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "score",
"target": 800,
"text": "Score 800 in Dino Run"
}
],
"file": "games/2d/dino-run.html",
"dim": "2d",
"modes": [
"sp"
]
},
{
"id": "tank-battle",
"n": 20,
"title": "TANK BATTLE",
"genre": "fun",
"modes": [
"sp",
"online",
"local"
],
"minPlayers": 2,
"maxPlayers": 4,
"desc": "Top-down tank brawl in a walled arena. Shells bounce off walls once, so angles matter. Three hits and you're scrap. Last tank rolling wins the round, first to 3 rounds wins. Bots fill empty seats.",
"controls": "↑ ↓ drive · ← → turn · Space fire (same screen: P1 WASD + Space, P2 arrows + Enter)",
"scoreLabel": "KILLS",
"tasks": [
{
"stat": "won",
"target": 1,
"text": "Win a match of Tank Battle"
},
{
"stat": "score",
"target": 5,
"text": "Destroy 5 tanks in Tank Battle"
}
],
"file": "games/2d/tank-battle.html",
"dim": "2d",
"cover": "games/covers/tank-battle.png"
},
{
"id": "neon-kart",
"n": 22,
"title": "NEON KART",
"genre": "fun",
"modes": [
"sp",
"online",
"local"
],
"minPlayers": 2,
"maxPlayers": 6,
"desc": "Top-down kart racing on glowing tracks. Drift through corners (hold Shift while turning) to charge a boost, hit the speed pads, bump the others off the line. Three laps, three tracks, up to six racers.",
"controls": "↑ accelerate · ↓ brake · ← → steer · Shift drift (release to boost) (same screen: P1 WASD + Space/Shift, P2 arrows + Enter/Right-Shift)",
"scoreLabel": "PLACE PTS",
"tasks": [
{
"stat": "won",
"target": 1,
"text": "Win a Neon Kart race"
}
],
"file": "games/2d/neon-kart.html",
"dim": "2d",
"cover": "games/covers/neon-kart.png"
},
{
"id": "frogger",
"n": 24,
"title": "FROGGER",
"genre": "fun",
"desc": "Hop the frog across five lanes of traffic and a river of logs and turtles into the five lily pads at the top. Fill all five to clear the level. Turtles sometimes dive. Don't fall in.",
"controls": "Arrow keys / WASD or swipe, one hop at a time",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "score",
"target": 500,
"text": "Score 500 in Frogger"
}
],
"file": "games/2d/frogger.html",
"dim": "2d",
"modes": [
"sp"
]
},
{
"id": "missile-defense",
"n": 27,
"title": "MISSILE DEFENSE",
"genre": "fun",
"desc": "Missiles rain on your six cities. Click where they will be, not where they are: your interceptor bursts at that point and the blast catches anything flying through. Three bases, limited ammo per wave. Splitting warheads arrive later.",
"controls": "Click / tap to fire at that spot (the nearest base with ammo shoots)",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "score",
"target": 3000,
"text": "Score 3000 in Missile Defense"
}
],
"file": "games/2d/missile-defense.html",
"dim": "2d",
"modes": [
"sp"
]
},
{
"id": "lumberjack",
"n": 44,
"title": "LUMBERJACK",
"genre": "fun",
"desc": "Chop the endless tree from the left or the right. Every chop drops the trunk one log; if a branch lands on your side, you're done. The timer drains fast, and every chop refills it a little.",
"controls": "← / A = chop left · → / D = chop right (or tap the left / right half of the screen)",
"scoreLabel": "LOGS",
"tasks": [
{
"stat": "score",
"target": 100,
"text": "Chop 100 logs in Lumberjack"
}
],
"file": "games/2d/lumberjack.html",
"dim": "2d",
"modes": [
"sp"
]
},
{
"id": "bomb-tag",
"n": 47,
"title": "BOMB TAG",
"genre": "fun",
"modes": [
"sp",
"online",
"local"
],
"minPlayers": 2,
"maxPlayers": 8,
"desc": "Hot potato with a fuse. Whoever holds the bomb is IT: touch someone to pass it on. When the fuse runs out, the holder is out. The fuse gets shorter every round. Last one standing wins.",
"controls": "Arrow keys / WASD (or the stick) to run · Space = sprint (same screen: P1 WASD + Space, P2 arrows + Enter)",
"scoreLabel": "PLACE",
"tasks": [
{
"stat": "won",
"target": 1,
"text": "Win a game of Bomb Tag"
}
],
"file": "games/2d/bomb-tag.html",
"dim": "2d",
"cover": "games/covers/bomb-tag.png"
},
{
"id": "bomber-arena",
"n": 59,
"title": "BOMBER ARENA",
"genre": "fun",
"modes": [
"sp",
"online",
"local"
],
"minPlayers": 2,
"maxPlayers": 4,
"desc": "Drop bombs, blast crates, grab power-ups (more bombs, bigger blasts, speed) and trap the others. Four corners, one survivor. First to 3 rounds. Bots fill empty corners.",
"controls": "Arrow keys / WASD to move · Space = drop a bomb (same screen: P1 WASD + Space, P2 arrows + Enter)",
"scoreLabel": "KILLS",
"tasks": [
{
"stat": "won",
"target": 1,
"text": "Win a Bomber Arena match"
}
],
"file": "games/2d/bomber-arena.html",
"dim": "2d",
"cover": "games/covers/bomber-arena.png"
},
{
"id": "air-hockey",
"n": 75,
"title": "AIR HOCKEY",
"genre": "fun",
"modes": [
"sp",
"online",
"local"
],
"minPlayers": 2,
"maxPlayers": 2,
"desc": "Slam the puck into the other goal. Hit it hard with a fast mallet, bank it off the walls. First to 7, against the CPU, a friend on one screen, or online.",
"controls": "Mouse / touch moves your mallet · same screen: left WASD, right arrows",
"scoreLabel": "GOALS",
"tasks": [
{
"stat": "won",
"target": 1,
"text": "Win a game of Air Hockey"
}
],
"file": "games/2d/air-hockey.html",
"dim": "2d",
"cover": "games/covers/air-hockey.png"
},
{
"id": "snake-arena",
"n": 76,
"title": "SNAKE ARENA",
"genre": "fun",
"modes": [
"sp",
"online",
"local"
],
"minPlayers": 2,
"maxPlayers": 8,
"desc": "Up to 8 snakes in one arena. Eat to grow, make others crash into you, and be the last one slithering. Fallen snakes turn into food. Bots fill empty seats.",
"controls": "Arrow keys / WASD or swipe · same screen: P1 WASD, P2 arrows",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "won",
"target": 1,
"text": "Be the last snake alive in Snake Arena"
}
],
"file": "games/2d/snake-arena.html",
"dim": "2d",
"cover": "games/covers/snake-arena.png"
},
{
"id": "reaction-duel",
"n": 77,
"title": "REACTION DUEL",
"genre": "fun",
"modes": [
"sp",
"online",
"local"
],
"minPlayers": 2,
"maxPlayers": 8,
"desc": "Wild-west quick draw for up to 8. Wait for DRAW!, then hit first. Jump early and you're out for that round. First to 5 round wins takes it.",
"controls": "Online: click / tap / Space · same screen: P1 = A, P2 = L",
"scoreLabel": "ROUNDS",
"tasks": [
{
"stat": "won",
"target": 1,
"text": "Win a Reaction Duel"
}
],
"file": "games/2d/reaction-duel.html",
"dim": "2d",
"cover": "games/covers/reaction-duel.png"
},
{
"id": "knife-throw",
"n": 95,
"title": "KNIFE THROW",
"genre": "fun",
"desc": "Throw every knife into the spinning log without hitting a knife that's already there. Apples on the log are bonus points. Every fifth log is a boss that spins backwards and speeds up without warning.",
"controls": "Space / click / tap to throw",
"scoreLabel": "KNIVES",
"tasks": [
{
"stat": "score",
"target": 40,
"text": "Stick 40 knives in Knife Throw"
}
],
"file": "games/2d/knife-throw.html",
"dim": "2d",
"modes": [
"sp"
]
},
{
"id": "typing-race",
"n": 98,
"title": "TYPING RACE",
"genre": "fun",
"modes": [
"sp",
"online"
],
"minPlayers": 2,
"maxPlayers": 8,
"desc": "Your car moves as fast as you type. Race up to 7 friends online on the same passage, or 3 ghost racers solo. Typos stop your car until you fix them.",
"controls": "Type the passage · Backspace fixes mistakes",
"scoreLabel": "WPM",
"tasks": [
{
"stat": "won",
"target": 1,
"text": "Win a Typing Race"
},
{
"stat": "score",
"target": 40,
"text": "Finish a Typing Race at 40 WPM"
}
],
"file": "games/2d/typing-race.html",
"dim": "2d",
"cover": "games/covers/typing-race.png"
},
{
"id": "2048",
"n": 1,
"title": "2048",
"genre": "mind",
"desc": "Slide the tiles, merge equal numbers, reach 2048. Keep going after that for a bigger score. One undo per game.",
"controls": "Arrow keys / WASD or swipe · U = undo once",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "score",
"target": 3000,
"text": "Score 3000 in 2048"
},
{
"stat": "tile",
"target": 512,
"text": "Make a 512 tile in 2048"
}
],
"file": "games/2d/2048.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/2048.png"
},
{
"id": "atlas",
"n": 2,
"title": "ATLAS",
"genre": "mind",
"desc": "The classic place-name chain against the CPU. Name a country that starts with the last letter of the one before. No repeats. 15 seconds a turn, and the CPU knows its geography.",
"controls": "Type (or tap the keyboard) · Enter to answer",
"scoreLabel": "COUNTRIES",
"tasks": [
{
"stat": "score",
"target": 8,
"text": "Name 8 countries in one Atlas game"
}
],
"file": "games/2d/atlas.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/atlas.png"
},
{
"id": "chess",
"n": 3,
"title": "CHESS",
"genre": "mind",
"modes": [
"sp",
"online",
"local"
],
"minPlayers": 2,
"maxPlayers": 2,
"desc": "Full chess: castling, en passant, promotion, check and mate. Play the CPU on EASY, MEDIUM or HARD, a friend on the same screen, or online (the leader plays white).",
"controls": "Click / tap a piece, then a highlighted square",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "won",
"target": 1,
"text": "Beat the CPU at Chess"
}
],
"file": "games/2d/chess.html",
"dim": "2d",
"cover": "games/covers/chess.png"
},
{
"id": "tic-tac-toe",
"n": 4,
"title": "TIC TAC TOE",
"genre": "mind",
"modes": [
"sp",
"online",
"local"
],
"minPlayers": 2,
"maxPlayers": 2,
"desc": "Best of 9 rounds. Solo, the CPU starts sloppy and gets sharper every round until it plays perfectly. Or play a friend on the same screen or online; the starting player swaps each round.",
"controls": "Click / tap a square (or 1-9 on the number pad layout)",
"scoreLabel": "WINS",
"tasks": [
{
"stat": "score",
"target": 3,
"text": "Win 3 rounds of Tic Tac Toe in one match"
}
],
"file": "games/2d/tic-tac-toe.html",
"dim": "2d",
"cover": "games/covers/tic-tac-toe.png"
},
{
"id": "wordle",
"n": 5,
"title": "WORDLE",
"genre": "mind",
"desc": "Guess the 5-letter word in 6 tries. Green = right letter, right spot. Yellow = in the word, wrong spot. Grey = not in the word. Solve as many words in a row as you can.",
"controls": "Type or tap the keyboard · Enter to guess",
"scoreLabel": "WORDS",
"tasks": [
{
"stat": "score",
"target": 3,
"text": "Solve 3 words in a row in Wordle"
}
],
"file": "games/2d/wordle.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/wordle.png"
},
{
"id": "aim-trainer",
"n": 6,
"title": "AIM TRAINER",
"genre": "mind",
"desc": "30 seconds. Targets shrink while they live, some drift, gold ones are worth triple. Misses cost points, so don't spray.",
"controls": "Click / tap the targets",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "score",
"target": 40,
"text": "Score 40 in Aim Trainer"
},
{
"stat": "accuracy",
"target": 90,
"text": "Get 90% accuracy in Aim Trainer"
}
],
"file": "games/2d/aim-trainer.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/aim-trainer.png"
},
{
"id": "reaction-test",
"n": 7,
"title": "REACTION TEST",
"genre": "mind",
"desc": "Wait for green, then hit as fast as you can. Five tries, your average counts. Click on red and that try is a fail. Fake-out colours show up from try 3.",
"controls": "Click / tap / Space when the screen turns GREEN",
"scoreLabel": "MS AVG",
"lowerIsBetter": true,
"tasks": [
{
"stat": "best",
"target": 1,
"text": "Finish a Reaction Test with no early clicks"
}
],
"file": "games/2d/reaction-test.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/reaction-test.png"
},
{
"id": "colour-quiz",
"n": 8,
"title": "COLOUR QUIZ",
"genre": "mind",
"desc": "One tile is a slightly different shade. Find it before the timer runs out. The grid grows and the difference shrinks every round.",
"controls": "Click / tap the odd tile",
"scoreLabel": "ROUNDS",
"tasks": [
{
"stat": "score",
"target": 15,
"text": "Reach round 15 in Colour Quiz"
}
],
"file": "games/2d/colour-quiz.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/colour-quiz.png"
},
{
"id": "sequence-memory",
"n": 9,
"title": "SEQUENCE MEMORY",
"genre": "mind",
"desc": "Squares light up one after another with a note each. Repeat the order. One more step every round, and it plays faster as you go.",
"controls": "Click / tap the squares (or keys 1-9)",
"scoreLabel": "STEPS",
"tasks": [
{
"stat": "score",
"target": 10,
"text": "Remember 10 steps in Sequence Memory"
}
],
"file": "games/2d/sequence-memory.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/sequence-memory.png"
},
{
"id": "typing-speed",
"n": 10,
"title": "TYPING SPEED",
"genre": "mind",
"desc": "60 seconds, real words. Your words-per-minute counts only correct words, so speed without accuracy gets you nowhere.",
"controls": "Type the highlighted word · Space moves to the next word",
"scoreLabel": "WPM",
"tasks": [
{
"stat": "score",
"target": 35,
"text": "Type 35 WPM in Typing Speed"
}
],
"file": "games/2d/typing-speed.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/typing-speed.png"
},
{
"id": "sudoku",
"n": 13,
"title": "SUDOKU",
"genre": "mind",
"desc": "Fill the grid so every row, column and 3×3 box has 1 to 9 once. Every puzzle is freshly generated with a single solution. Pick EASY, MEDIUM or HARD. Pencil marks, 3 mistakes allowed, faster solves score more.",
"controls": "Click a cell, then a number (keys 1-9) · N = pencil mode · Backspace = erase",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "won",
"target": 1,
"text": "Solve a Sudoku"
}
],
"file": "games/2d/sudoku.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/sudoku.png"
},
{
"id": "minesweeper",
"n": 14,
"title": "MINESWEEPER",
"genre": "mind",
"desc": "Clear the field without touching a mine. Numbers tell you how many mines touch that square. The first click is always safe. Flag what you know, chord a number to clear around it.",
"controls": "Click = dig · right-click (or F mode button) = flag · click a number with all flags placed = clear around it",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "won",
"target": 1,
"text": "Clear a Minesweeper field"
}
],
"file": "games/2d/minesweeper.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/minesweeper.png"
},
{
"id": "connect-four",
"n": 15,
"title": "CONNECT FOUR",
"genre": "mind",
"modes": [
"sp",
"online",
"local"
],
"minPlayers": 2,
"maxPlayers": 2,
"desc": "Drop discs, get four in a row: across, down or diagonal. Solo against a CPU that looks 5 moves ahead, with a friend on one screen, or online.",
"controls": "Click / tap a column (or 1-7)",
"scoreLabel": "WINS",
"tasks": [
{
"stat": "won",
"target": 1,
"text": "Win a game of Connect Four"
}
],
"file": "games/2d/connect-four.html",
"dim": "2d",
"cover": "games/covers/connect-four.png"
},
{
"id": "sliding-puzzle",
"n": 17,
"title": "SLIDING PUZZLE",
"genre": "mind",
"desc": "The classic 15-puzzle, plus 3×3 and 5×5. Slide tiles into the gap until the numbers are in order. Fewer moves and less time score more.",
"controls": "Click / tap a tile next to the gap, or arrow keys",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "won",
"target": 1,
"text": "Solve a Sliding Puzzle"
}
],
"file": "games/2d/sliding-puzzle.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/sliding-puzzle.png"
},
{
"id": "mastermind",
"n": 19,
"title": "MASTERMIND",
"genre": "mind",
"desc": "Crack the hidden 4-colour code in 10 tries. After each guess: a white peg = right colour in the right spot, a grey peg = right colour, wrong spot. Colours can repeat.",
"controls": "Click a colour to fill the next slot · click a slot to clear it · CHECK to guess",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "won",
"target": 1,
"text": "Crack a Mastermind code"
}
],
"file": "games/2d/mastermind.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/mastermind.png"
},
{
"id": "lights-out",
"n": 23,
"title": "LIGHTS OUT",
"genre": "mind",
"desc": "Pressing a light flips it and its four neighbours. Turn every light off. Ten boards that get harder, each one guaranteed solvable. Stuck? A hint costs points.",
"controls": "Click / tap a light · H = hint",
"scoreLabel": "BOARDS",
"tasks": [
{
"stat": "score",
"target": 5,
"text": "Solve 5 Lights Out boards"
}
],
"file": "games/2d/lights-out.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/lights-out.png"
},
{
"id": "hangman",
"n": 26,
"title": "HANGMAN",
"genre": "mind",
"desc": "Guess the word one letter at a time before the little robot is fully built. Six wrong letters and it's game over. Solve words in a row for a streak; longer words are worth more.",
"controls": "Type or tap letters",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "score",
"target": 40,
"text": "Score 40 in Hangman"
}
],
"file": "games/2d/hangman.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/hangman.png"
},
{
"id": "quiz-battle",
"n": 86,
"title": "QUIZ BATTLE",
"genre": "mind",
"modes": [
"sp",
"online"
],
"minPlayers": 2,
"maxPlayers": 8,
"desc": "Ten trivia questions, everyone answers at the same time. Right answers score more the faster you are, and a streak adds a bonus. Online for up to 8, or solo against three quiz bots.",
"controls": "Click / tap an answer (or 1-4)",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "won",
"target": 1,
"text": "Win a Quiz Battle"
},
{
"stat": "score",
"target": 600,
"text": "Score 600 in Quiz Battle"
}
],
"file": "games/2d/quiz-battle.html",
"dim": "2d",
"cover": "games/covers/quiz-battle.png"
},
{
"id": "match-3",
"n": 1,
"title": "MATCH-3",
"genre": "relax",
"desc": "Swap neighbouring gems to line up three or more. Four in a row makes a line-blaster, five makes a colour bomb. 30 calm moves, no timer.",
"controls": "Click a gem then a neighbour, or drag / swipe",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "score",
"target": 3000,
"text": "Score 3000 in Match-3"
}
],
"file": "games/2d/match-3.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/match-3.png"
},
{
"id": "word-connect",
"n": 2,
"title": "WORD CONNECT",
"genre": "relax",
"desc": "Swipe across the letter wheel to spell words and fill every slot. Extra real words count as bonus words. Ten calm levels, no timer.",
"controls": "Drag across the letters (or type + Enter) · Shuffle button mixes the wheel",
"scoreLabel": "WORDS",
"tasks": [
{
"stat": "score",
"target": 20,
"text": "Find 20 words in Word Connect"
}
],
"file": "games/2d/word-connect.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/word-connect.png"
},
{
"id": "mystery-cafe",
"n": 3,
"title": "MYSTERY CAFÉ",
"genre": "relax",
"desc": "Run a cozy café for three days. Read what each guest wants and serve the right drink. Something goes missing every day, and the guests let slip clues. Close up and name who did it.",
"controls": "Click / tap a drink to serve it · pick the culprit at closing time",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "solved",
"target": 2,
"text": "Solve 2 café mysteries in one game"
}
],
"file": "games/2d/mystery-cafe.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/mystery-cafe.png"
},
{
"id": "battleship",
"n": 4,
"title": "BATTLESHIP",
"genre": "relax",
"desc": "Sink the CPU fleet before it sinks yours. Your ships are placed for you (R to shuffle before the first shot). The CPU hunts smartly once it finds you.",
"controls": "Click / tap the enemy sea to fire · R = shuffle your fleet before you start",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "won",
"target": 1,
"text": "Win a game of Battleship"
}
],
"file": "games/2d/battleship.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/battleship.png"
},
{
"id": "solitaire",
"n": 7,
"title": "SOLITAIRE",
"genre": "relax",
"desc": "Classic Klondike. Build the four suits up from Ace to King, stack the table down in alternating colours. Drag cards, or just tap one and it jumps to the best spot. No timer, undo as much as you like.",
"controls": "Drag cards · tap a card to auto-move · tap the deck to draw · U = undo",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "won",
"target": 1,
"text": "Win a game of Solitaire"
},
{
"stat": "score",
"target": 300,
"text": "Score 300 in Solitaire"
}
],
"file": "games/2d/solitaire.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/solitaire.png"
},
{
"id": "block-blast",
"n": 11,
"title": "BLOCK BLAST",
"genre": "relax",
"desc": "Drag the three pieces onto the 8×8 board. Fill a whole row or column and it clears. Clear several at once for a combo. When none of your pieces fit anywhere, it's over. No timer.",
"controls": "Drag pieces onto the board",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "score",
"target": 800,
"text": "Score 800 in Block Blast"
}
],
"file": "games/2d/block-blast.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/block-blast.png"
},
{
"id": "bubble-shooter",
"n": 12,
"title": "BUBBLE SHOOTER",
"genre": "relax",
"desc": "Aim, bounce off the walls, and pop groups of three or more matching bubbles. Anything left hanging falls for bonus points. Every few shots the ceiling drops a row, so plan ahead.",
"controls": "Aim with the mouse / touch, click to shoot · Space swaps the next bubble",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "score",
"target": 1500,
"text": "Score 1500 in Bubble Shooter"
}
],
"file": "games/2d/bubble-shooter.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/bubble-shooter.png"
},
{
"id": "zen-sand",
"n": 14,
"title": "ZEN SAND",
"genre": "relax",
"desc": "A quiet sand garden. Rake flowing lines around the stones, change rake width, drop new stones and moss, smooth it all out and start again. Soft wind and water in the background. No goals, no timer.",
"controls": "Drag to rake · 1/2/3 rake width · S = place a stone · M = moss · C = smooth the sand · DONE when you finish",
"scoreLabel": "MINUTES",
"tasks": [
{
"stat": "score",
"target": 2,
"text": "Rake the Zen Sand garden for 2 minutes"
}
],
"file": "games/2d/zen-sand.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/zen-sand.png"
},
{
"id": "word-search",
"n": 15,
"title": "WORD SEARCH",
"genre": "relax",
"desc": "Find the hidden words in the letter grid: across, down, diagonal and backwards. Each puzzle has a theme. Drag across a word to circle it. No timer, five puzzles.",
"controls": "Drag from the first letter to the last",
"scoreLabel": "WORDS",
"tasks": [
{
"stat": "score",
"target": 20,
"text": "Find 20 words in Word Search"
}
],
"file": "games/2d/word-search.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/word-search.png"
},
{
"id": "ball-sort",
"n": 16,
"title": "BALL SORT",
"genre": "relax",
"desc": "Sort the coloured balls so every tube holds one colour. You can only put a ball on top of the same colour or into an empty tube. Levels add colours; undo is free.",
"controls": "Click / tap a tube to lift its top ball, then tap where it goes · U = undo",
"scoreLabel": "LEVELS",
"tasks": [
{
"stat": "score",
"target": 5,
"text": "Clear 5 Ball Sort levels"
}
],
"file": "games/2d/ball-sort.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/ball-sort.png"
},
{
"id": "gravity-flip",
"n": 1,
"title": "GRAVITY FLIP",
"genre": "mystery",
"desc": "You can't jump. You can only flip gravity: floor to ceiling and back. Spikes on both sides, gaps in the track, and every so often the level fights back by flipping YOUR gravity for you.",
"controls": "Space / click / tap = flip gravity",
"scoreLabel": "METRES",
"tasks": [
{
"stat": "score",
"target": 500,
"text": "Run 500 m in Gravity Flip"
}
],
"file": "games/2d/gravity-flip.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/gravity-flip.png"
},
{
"id": "mirror-mode",
"n": 2,
"title": "MIRROR MODE",
"genre": "mystery",
"desc": "You control two runners at once with the same keys, but the bottom one is mirrored: when the top goes left, the bottom goes right. Blocks rain on both worlds. Keep BOTH alive and grab the stars.",
"controls": "← → / A D (or drag) moves both, mirrored",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "score",
"target": 40,
"text": "Score 40 in Mirror Mode"
}
],
"file": "games/2d/mirror-mode.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/mirror-mode.png"
},
{
"id": "the-button",
"n": 3,
"title": "THE BUTTON",
"genre": "mystery",
"desc": "There is a button. Do not press it. The game will beg, bribe, trick and threaten you. Every second you hold out is a point. Last two minutes and the game gives up. There are several endings.",
"controls": "Don't click the button. (Everything else you can click.)",
"scoreLabel": "SECONDS",
"tasks": [
{
"stat": "score",
"target": 120,
"text": "Never press The Button"
}
],
"file": "games/2d/the-button.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/the-button.png"
},
{
"id": "wrong-controls",
"n": 4,
"title": "WRONG CONTROLS",
"genre": "mystery",
"desc": "Grab coins and dodge the chasers. Easy, except every few seconds your controls get scrambled: up might be left, left might be down. The panel shows the new mapping. Keep up.",
"controls": "Arrow keys / WASD (or swipe-drag) - but they won't stay that way",
"scoreLabel": "COINS",
"tasks": [
{
"stat": "score",
"target": 20,
"text": "Grab 20 coins in Wrong Controls"
}
],
"file": "games/2d/wrong-controls.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/wrong-controls.png"
},
{
"id": "tiny-planet",
"n": 5,
"title": "TINY PLANET",
"genre": "mystery",
"desc": "Run laps around a planet the size of a house. Jump the rocks that grow out of the ground, grab gems, and watch out: the planet spins faster and shrinks a little with every lap.",
"controls": "Space / ↑ / tap = jump (hold for higher) · ← → change direction",
"scoreLabel": "GEMS",
"tasks": [
{
"stat": "score",
"target": 15,
"text": "Collect 15 gems on Tiny Planet"
}
],
"file": "games/2d/tiny-planet.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/tiny-planet.png"
},
{
"id": "cursor-chaos",
"n": 11,
"title": "CURSOR CHAOS",
"genre": "mystery",
"desc": "Your mouse pointer IS the hero. Sweep up the data bits while antivirus blobs hunt your cursor. Move too fast and you glitch out of control. The screen keeps adding hostile UI.",
"controls": "Move the mouse / drag your finger. That's it.",
"scoreLabel": "BITS",
"tasks": [
{
"stat": "score",
"target": 40,
"text": "Collect 40 bits in Cursor Chaos"
}
],
"cursor": "off",
"file": "games/2d/cursor-chaos.html",
"dim": "2d",
"modes": [
"sp"
],
"cover": "games/covers/cursor-chaos.png"
},
{
"id": "sumo-push",
"n": 12,
"title": "SUMO PUSH",
"genre": "mystery",
"modes": [
"sp",
"online",
"local"
],
"minPlayers": 2,
"maxPlayers": 8,
"desc": "Up to 8 bouncy blobs on a shrinking ring. Bump everyone off, dash into them, and stay on. The floor gets smaller every few seconds and sometimes turns to ice. Last blob standing wins the round, first to 3.",
"controls": "Move with arrows / WASD (or the stick) · Space = DASH (same screen: P1 WASD + Space, P2 arrows + Enter)",
"scoreLabel": "KNOCKOUTS",
"tasks": [
{
"stat": "won",
"target": 1,
"text": "Win a Sumo Push match"
}
],
"file": "games/2d/sumo-push.html",
"dim": "2d",
"cover": "games/covers/sumo-push.png"
},
{
"id": "draw-guess",
"n": 89,
"title": "DRAW & GUESS",
"genre": "mystery",
"modes": [
"online"
],
"minPlayers": 2,
"maxPlayers": 8,
"desc": "Party drawing game for 2-8. One player draws a secret word, everyone else races to guess it. Faster guesses score more, and the artist scores for every correct guess. Everyone draws once.",
"controls": "Drawing: drag on the canvas, pick colours / sizes · Guessing: type (or tap) + Enter",
"scoreLabel": "POINTS",
"tasks": [
{
"stat": "won",
"target": 1,
"text": "Win a game of Draw & Guess"
}
],
"file": "games/2d/draw-guess.html",
"dim": "2d",
"cover": "games/covers/draw-guess.png"
},
{
"id": "together",
"n": 100,
"title": "TOGETHER",
"genre": "mystery",
"modes": [
"sp",
"online",
"local"
],
"minPlayers": 2,
"maxPlayers": 4,
"desc": "A co-op puzzle platformer: nobody gets out alone. Stand on each other's heads to reach high ledges, hold buttons so a friend can pass, carry the key to the door. Eight levels. Everyone must reach the exit. Solo, you swap between two little blobs.",
"controls": "← → / A D move · ↑ / W / Space jump · solo: Tab or Q swaps blob (same screen: P1 WASD, P2 arrows + Enter to jump)",
"scoreLabel": "LEVELS",
"tasks": [
{
"stat": "score",
"target": 4,
"text": "Clear 4 levels of Together"
}
],
"file": "games/2d/together.html",
"dim": "2d",
"cover": "games/covers/together.png"
}
];
