/* Trivia bank: window.TRIVIA = [[question, correct, wrong, wrong, wrong, category], ...]  */
window.TRIVIA = [
  ['What is the largest planet in our solar system?', 'Jupiter', 'Saturn', 'Neptune', 'Earth', 'SPACE'],
  ['Which planet is known as the Red Planet?', 'Mars', 'Venus', 'Mercury', 'Jupiter', 'SPACE'],
  ['How many planets are in our solar system?', '8', '9', '7', '10', 'SPACE'],
  ['What is the closest star to Earth?', 'The Sun', 'Sirius', 'Polaris', 'Alpha Centauri A', 'SPACE'],
  ['Which planet has the most famous rings?', 'Saturn', 'Uranus', 'Mars', 'Mercury', 'SPACE'],
  ['What do we call a rock from space that lands on Earth?', 'Meteorite', 'Comet', 'Asteroid belt', 'Nebula', 'SPACE'],
  ['Who was the first person to walk on the Moon?', 'Neil Armstrong', 'Buzz Aldrin', 'Yuri Gagarin', 'Michael Collins', 'SPACE'],
  ['What galaxy do we live in?', 'The Milky Way', 'Andromeda', 'Triangulum', 'Sombrero', 'SPACE'],
  ['Which planet is closest to the Sun?', 'Mercury', 'Venus', 'Mars', 'Earth', 'SPACE'],
  ['What gas do plants take in from the air?', 'Carbon dioxide', 'Oxygen', 'Nitrogen', 'Helium', 'SCIENCE'],
  ['What is H2O better known as?', 'Water', 'Salt', 'Hydrogen gas', 'Air', 'SCIENCE'],
  ['How many bones are in an adult human body?', '206', '186', '256', '300', 'SCIENCE'],
  ['What is the hardest natural substance?', 'Diamond', 'Gold', 'Iron', 'Quartz', 'SCIENCE'],
  ['What part of the cell holds its DNA?', 'Nucleus', 'Membrane', 'Ribosome', 'Cytoplasm', 'SCIENCE'],
  ['At what temperature does water boil at sea level?', '100 °C', '90 °C', '120 °C', '80 °C', 'SCIENCE'],
  ['Which organ pumps blood around the body?', 'Heart', 'Lungs', 'Liver', 'Brain', 'SCIENCE'],
  ['What force keeps us on the ground?', 'Gravity', 'Magnetism', 'Friction', 'Inertia', 'SCIENCE'],
  ['What is the chemical symbol for gold?', 'Au', 'Ag', 'Gd', 'Go', 'SCIENCE'],
  ['What is the largest organ of the human body?', 'Skin', 'Liver', 'Brain', 'Heart', 'SCIENCE'],
  ['Which animal is the largest mammal?', 'Blue whale', 'Elephant', 'Giraffe', 'Hippo', 'NATURE'],
  ['What is the fastest land animal?', 'Cheetah', 'Lion', 'Horse', 'Greyhound', 'NATURE'],
  ['How many legs does a spider have?', '8', '6', '10', '12', 'NATURE'],
  ['What do bees make?', 'Honey', 'Milk', 'Silk', 'Wax only', 'NATURE'],
  ['Which bird is known for copying human speech?', 'Parrot', 'Owl', 'Eagle', 'Penguin', 'NATURE'],
  ['What is a baby kangaroo called?', 'Joey', 'Cub', 'Kit', 'Calf', 'NATURE'],
  ['Which animal is known as the King of the Jungle?', 'Lion', 'Tiger', 'Gorilla', 'Elephant', 'NATURE'],
  ['How many hearts does an octopus have?', '3', '1', '2', '8', 'NATURE'],
  ['What is the only mammal that can truly fly?', 'Bat', 'Flying squirrel', 'Sugar glider', 'Colugo', 'NATURE'],
  ['Which tree do acorns come from?', 'Oak', 'Pine', 'Maple', 'Birch', 'NATURE'],
  ['What is the capital of France?', 'Paris', 'Lyon', 'Marseille', 'Nice', 'WORLD'],
  ['What is the capital of Japan?', 'Tokyo', 'Kyoto', 'Osaka', 'Seoul', 'WORLD'],
  ['What is the capital of India?', 'New Delhi', 'Mumbai', 'Kolkata', 'Bengaluru', 'WORLD'],
  ['What is the capital of Australia?', 'Canberra', 'Sydney', 'Melbourne', 'Perth', 'WORLD'],
  ['What is the capital of Canada?', 'Ottawa', 'Toronto', 'Vancouver', 'Montreal', 'WORLD'],
  ['Which is the longest river in the world (by most measurements)?', 'Nile', 'Amazon', 'Yangtze', 'Mississippi', 'WORLD'],
  ['Which is the largest ocean?', 'Pacific', 'Atlantic', 'Indian', 'Arctic', 'WORLD'],
  ['Mount Everest is on the border of Nepal and which country?', 'China', 'India', 'Bhutan', 'Pakistan', 'WORLD'],
  ['Which country has the most people (2024)?', 'India', 'China', 'USA', 'Indonesia', 'WORLD'],
  ['In which country are the ancient pyramids of Giza?', 'Egypt', 'Mexico', 'Peru', 'Sudan', 'WORLD'],
  ['What is the largest desert in the world?', 'Antarctica', 'Sahara', 'Gobi', 'Arabian', 'WORLD'],
  ['Which continent is Kenya in?', 'Africa', 'Asia', 'South America', 'Europe', 'WORLD'],
  ['What is the smallest country in the world?', 'Vatican City', 'Monaco', 'Malta', 'San Marino', 'WORLD'],
  ['Which city is known as the Big Apple?', 'New York', 'Los Angeles', 'Chicago', 'Boston', 'WORLD'],
  ['The Eiffel Tower is made mostly of what?', 'Iron', 'Steel and glass', 'Stone', 'Aluminium', 'WORLD'],
  ['Which country is shaped like a boot?', 'Italy', 'Spain', 'Greece', 'Portugal', 'WORLD'],
  ['What currency is used in Japan?', 'Yen', 'Won', 'Yuan', 'Rupee', 'WORLD'],
  ['How many continents are there?', '7', '5', '6', '8', 'WORLD'],
  ['What is 12 × 12?', '144', '124', '132', '154', 'MATHS'],
  ['What is the square root of 81?', '9', '8', '7', '11', 'MATHS'],
  ['How many sides does a hexagon have?', '6', '5', '7', '8', 'MATHS'],
  ['What is 15% of 200?', '30', '15', '20', '45', 'MATHS'],
  ['How many degrees are in a right angle?', '90', '180', '45', '60', 'MATHS'],
  ['What is the next prime number after 7?', '11', '9', '13', '10', 'MATHS'],
  ['How many minutes are in 3 hours?', '180', '120', '200', '160', 'MATHS'],
  ['What is 1000 ÷ 8?', '125', '120', '150', '100', 'MATHS'],
  ['What is the value of π rounded to 2 decimals?', '3.14', '3.41', '3.12', '3.16', 'MATHS'],
  ['How many seconds are in a minute?', '60', '100', '30', '90', 'MATHS'],
  ['What is 7 × 8?', '56', '54', '64', '48', 'MATHS'],
  ['A triangle\'s angles always add up to…', '180°', '360°', '90°', '270°', 'MATHS'],
  ['What is the Roman numeral for 50?', 'L', 'C', 'D', 'X', 'MATHS'],
  ['Who painted the Mona Lisa?', 'Leonardo da Vinci', 'Picasso', 'Van Gogh', 'Michelangelo', 'ART'],
  ['How many strings does a standard guitar have?', '6', '4', '5', '7', 'MUSIC'],
  ['How many keys are on a standard piano?', '88', '76', '61', '100', 'MUSIC'],
  ['Which instrument has black and white keys?', 'Piano', 'Violin', 'Flute', 'Drum', 'MUSIC'],
  ['What colour do you get mixing blue and yellow?', 'Green', 'Purple', 'Orange', 'Brown', 'ART'],
  ['What are the three primary colours of light?', 'Red, green, blue', 'Red, yellow, blue', 'Cyan, magenta, yellow', 'Red, white, blue', 'ART'],
  ['Who wrote "Romeo and Juliet"?', 'William Shakespeare', 'Charles Dickens', 'Jane Austen', 'Mark Twain', 'BOOKS'],
  ['Which wizard school does Harry Potter attend?', 'Hogwarts', 'Durmstrang', 'Beauxbatons', 'Ilvermorny', 'BOOKS'],
  ['In "The Jungle Book", what kind of animal is Baloo?', 'Bear', 'Panther', 'Tiger', 'Wolf', 'BOOKS'],
  ['Who is Sherlock Holmes\'s friend and assistant?', 'Dr. Watson', 'Moriarty', 'Lestrade', 'Mycroft', 'BOOKS'],
  ['What is the name of the toy cowboy in "Toy Story"?', 'Woody', 'Buzz', 'Jessie', 'Slinky', 'MOVIES'],
  ['Which film features a fish called Nemo?', 'Finding Nemo', 'Shark Tale', 'Moana', 'The Little Mermaid', 'MOVIES'],
  ['What is the name of Mickey Mouse\'s dog?', 'Pluto', 'Goofy', 'Max', 'Spike', 'MOVIES'],
  ['In "Frozen", what is the name of the snowman?', 'Olaf', 'Sven', 'Kristoff', 'Hans', 'MOVIES'],
  ['Which superhero is known as the Dark Knight?', 'Batman', 'Superman', 'Iron Man', 'Spider-Man', 'MOVIES'],
  ['What colour is the Hulk?', 'Green', 'Red', 'Blue', 'Grey', 'MOVIES'],
  ['Which company makes the PlayStation?', 'Sony', 'Nintendo', 'Microsoft', 'Sega', 'GAMES'],
  ['What is Mario\'s brother called?', 'Luigi', 'Wario', 'Toad', 'Yoshi', 'GAMES'],
  ['In Minecraft, what explodes when it gets close to you?', 'Creeper', 'Zombie', 'Skeleton', 'Enderman', 'GAMES'],
  ['What shape are the pieces in Tetris made of?', '4 squares', '3 squares', '5 squares', 'Triangles', 'GAMES'],
  ['Which game has a yellow character eating dots and avoiding ghosts?', 'Pac-Man', 'Frogger', 'Galaga', 'Donkey Kong', 'GAMES'],
  ['In chess, which piece can only move diagonally?', 'Bishop', 'Rook', 'Knight', 'King', 'GAMES'],
  ['How many squares are on a chessboard?', '64', '81', '100', '48', 'GAMES'],
  ['What is the most-sold video game console family of all time (approx.)?', 'PlayStation 2', 'Game Boy', 'Wii', 'Xbox 360', 'GAMES'],
  ['In which sport do you hear "love" as a score?', 'Tennis', 'Golf', 'Cricket', 'Football', 'SPORT'],
  ['How many players does a football (soccer) team have on the field?', '11', '9', '10', '12', 'SPORT'],
  ['How often are the Summer Olympics held?', 'Every 4 years', 'Every 2 years', 'Every year', 'Every 5 years', 'SPORT'],
  ['In cricket, how many balls are in an over?', '6', '5', '8', '10', 'SPORT'],
  ['What is the national sport of Japan?', 'Sumo', 'Karate', 'Baseball', 'Judo', 'SPORT'],
  ['How many rings are on the Olympic flag?', '5', '4', '6', '7', 'SPORT'],
  ['Which sport uses a shuttlecock?', 'Badminton', 'Tennis', 'Squash', 'Table tennis', 'SPORT'],
  ['How long is a marathon (approx.)?', '42 km', '26 km', '50 km', '21 km', 'SPORT'],
  ['What does "www" stand for?', 'World Wide Web', 'Wide World Web', 'Web World Wide', 'World Web Wide', 'TECH'],
  ['What does CPU stand for?', 'Central Processing Unit', 'Computer Power Unit', 'Core Program Unit', 'Central Program Utility', 'TECH'],
  ['Which company made the first iPhone?', 'Apple', 'Samsung', 'Nokia', 'Google', 'TECH'],
  ['How many bits are in a byte?', '8', '4', '16', '10', 'TECH'],
  ['What is the binary number for 5?', '101', '110', '111', '100', 'TECH'],
  ['What does a mouse cursor usually look like?', 'An arrow', 'A circle', 'A star', 'A square', 'TECH'],
  ['Which language is used to style web pages?', 'CSS', 'SQL', 'C++', 'Python', 'TECH'],
  ['What does "AI" stand for?', 'Artificial Intelligence', 'Automatic Input', 'Advanced Internet', 'Analog Interface', 'TECH'],
  ['Which fruit is known for keeping the doctor away?', 'Apple', 'Banana', 'Orange', 'Grape', 'FOOD'],
  ['Which country is famous for pizza and pasta?', 'Italy', 'France', 'Mexico', 'Greece', 'FOOD'],
  ['What is the main ingredient in guacamole?', 'Avocado', 'Tomato', 'Pea', 'Cucumber', 'FOOD'],
  ['Sushi comes from which country?', 'Japan', 'China', 'Thailand', 'Korea', 'FOOD'],
  ['What is a dried grape called?', 'Raisin', 'Prune', 'Date', 'Fig', 'FOOD'],
  ['Which vegetable makes your eyes water when you cut it?', 'Onion', 'Carrot', 'Potato', 'Cabbage', 'FOOD'],
  ['Which nut is used to make marzipan?', 'Almond', 'Peanut', 'Cashew', 'Walnut', 'FOOD'],
  ['What colour is a ripe banana?', 'Yellow', 'Green', 'Red', 'Purple', 'FOOD'],
  ['How many days are in a leap year?', '366', '365', '364', '360', 'GENERAL'],
  ['What is the opposite of "ancient"?', 'Modern', 'Old', 'Antique', 'Historic', 'WORDS'],
  ['Which word means "very happy"?', 'Ecstatic', 'Gloomy', 'Weary', 'Anxious', 'WORDS'],
  ['What is a word that sounds the same but has a different meaning called?', 'Homophone', 'Synonym', 'Antonym', 'Acronym', 'WORDS'],
  ['How many letters are in the English alphabet?', '26', '24', '28', '25', 'WORDS'],
  ['What is the plural of "mouse"?', 'Mice', 'Mouses', 'Meese', 'Mouse', 'WORDS'],
  ['Which month has the fewest days?', 'February', 'April', 'June', 'November', 'GENERAL'],
  ['How many hours are in a day?', '24', '12', '48', '36', 'GENERAL'],
  ['What do you call a shape with 8 sides?', 'Octagon', 'Hexagon', 'Pentagon', 'Decagon', 'MATHS'],
  ['Which is the coldest continent?', 'Antarctica', 'Asia', 'Europe', 'North America', 'WORLD'],
  ['What is frozen water called?', 'Ice', 'Steam', 'Mist', 'Dew', 'SCIENCE'],
  ['What colour are emeralds?', 'Green', 'Red', 'Blue', 'Yellow', 'GENERAL'],
  ['Which planet spins on its side?', 'Uranus', 'Neptune', 'Venus', 'Mars', 'SPACE'],
  ['What is the tallest animal?', 'Giraffe', 'Elephant', 'Camel', 'Ostrich', 'NATURE'],
  ['Which bird can\'t fly but is the fastest runner?', 'Ostrich', 'Penguin', 'Kiwi', 'Emu', 'NATURE'],
  ['What is the main language spoken in Brazil?', 'Portuguese', 'Spanish', 'English', 'French', 'WORLD'],
  ['How many players are on a basketball team on court?', '5', '6', '7', '4', 'SPORT'],
  ['What do caterpillars turn into?', 'Butterflies or moths', 'Beetles', 'Bees', 'Spiders', 'NATURE'],
  ['Which famous ship sank in 1912?', 'Titanic', 'Lusitania', 'Bismarck', 'Endeavour', 'HISTORY'],
  ['Who was the first President of the USA?', 'George Washington', 'Abraham Lincoln', 'Thomas Jefferson', 'John Adams', 'HISTORY'],
  ['Which ancient people built Machu Picchu?', 'The Inca', 'The Maya', 'The Aztecs', 'The Romans', 'HISTORY'],
  ['In which year did humans first land on the Moon?', '1969', '1959', '1979', '1972', 'HISTORY'],
  ['What wall was built across northern China?', 'The Great Wall', 'Hadrian\'s Wall', 'The Berlin Wall', 'The Red Wall', 'HISTORY'],
  ['Who discovered penicillin?', 'Alexander Fleming', 'Marie Curie', 'Louis Pasteur', 'Isaac Newton', 'HISTORY'],
];
