"""Scan games/**/*.html for <script type="application/json" id="meta"> and write js/games-data.js.

Run from the project root:  python tools/build_registry.py
"""
import json, os, re, glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
META_RE = re.compile(r'<script type="application/json" id="meta">(.*?)</script>', re.S)
ORDER = {'horror': 0, 'fun': 1, 'mind': 2, 'relax': 3, 'mystery': 4}

games = []
for path in sorted(glob.glob(os.path.join(ROOT, 'games', '2d', '*.html')) + glob.glob(os.path.join(ROOT, 'games', '3d', '*.html'))):
    src = open(path, encoding='utf-8').read()
    m = META_RE.search(src)
    if not m:
        print('NO META', path)
        continue
    meta = json.loads(m.group(1))
    rel = os.path.relpath(path, ROOT).replace('\\', '/')
    meta['file'] = rel
    meta.setdefault('dim', '2d')
    meta.setdefault('modes', ['sp'])
    cover = f"games/covers/{meta['id']}.png"
    if os.path.exists(os.path.join(ROOT, cover)):
        meta['cover'] = cover
    games.append(meta)

games.sort(key=lambda g: (ORDER.get(g.get('genre'), 9), g.get('n', 999), g['title']))
ids = [g['id'] for g in games]
dups = {i for i in ids if ids.count(i) > 1}
if dups:
    raise SystemExit(f'duplicate ids: {dups}')

out = '// AUTO-GENERATED by tools/build_registry.py - do not edit by hand.\nexport const GAME_LIST = ' + json.dumps(games, ensure_ascii=False, indent=0) + ';\n'
open(os.path.join(ROOT, 'js', 'games-data.js'), 'w', encoding='utf-8').write(out)
by = {}
for g in games:
    by[g['genre']] = by.get(g['genre'], 0) + 1
print(f'{len(games)} games', by)
