// The parts of Babylon.js (+ glTF loader) and Rapier that the NOVEX 3D games use. Deep imports keep the bundle small.
// Built by tools/kit3d/build.mjs into games/kit3d/vendor.js - edit this list, then `npm run build`.
export { Engine } from '@babylonjs/core/Engines/engine';
export { Scene } from '@babylonjs/core/scene';
export { FreeCamera } from '@babylonjs/core/Cameras/freeCamera';
export { TargetCamera } from '@babylonjs/core/Cameras/targetCamera';
export { Vector3, Vector2, Vector4, Quaternion, Matrix } from '@babylonjs/core/Maths/math.vector';
export { Camera } from '@babylonjs/core/Cameras/camera';
export { Color3, Color4 } from '@babylonjs/core/Maths/math.color';
export { Viewport } from '@babylonjs/core/Maths/math.viewport';
export { Scalar } from '@babylonjs/core/Maths/math.scalar';
export { Mesh } from '@babylonjs/core/Meshes/mesh';
export { TransformNode } from '@babylonjs/core/Meshes/transformNode';
export { InstancedMesh } from '@babylonjs/core/Meshes/instancedMesh';
export { VertexData } from '@babylonjs/core/Meshes/mesh.vertexData';
export { CreateBox } from '@babylonjs/core/Meshes/Builders/boxBuilder';
export { CreateSphere } from '@babylonjs/core/Meshes/Builders/sphereBuilder';
export { CreateCylinder } from '@babylonjs/core/Meshes/Builders/cylinderBuilder';
export { CreatePlane } from '@babylonjs/core/Meshes/Builders/planeBuilder';
export { CreateGround } from '@babylonjs/core/Meshes/Builders/groundBuilder';
export { CreateCapsule } from '@babylonjs/core/Meshes/Builders/capsuleBuilder';
export { CreateTorus } from '@babylonjs/core/Meshes/Builders/torusBuilder';
export { CreateDisc } from '@babylonjs/core/Meshes/Builders/discBuilder';
export { CreateLines } from '@babylonjs/core/Meshes/Builders/linesBuilder';
export { StandardMaterial } from '@babylonjs/core/Materials/standardMaterial';
export { PBRMaterial } from '@babylonjs/core/Materials/PBR/pbrMaterial';
export { Texture } from '@babylonjs/core/Materials/Textures/texture';
export { DynamicTexture } from '@babylonjs/core/Materials/Textures/dynamicTexture';
export { HemisphericLight } from '@babylonjs/core/Lights/hemisphericLight';
export { DirectionalLight } from '@babylonjs/core/Lights/directionalLight';
export { PointLight } from '@babylonjs/core/Lights/pointLight';
export { SpotLight } from '@babylonjs/core/Lights/spotLight';
export { ShadowGenerator } from '@babylonjs/core/Lights/Shadows/shadowGenerator';
import '@babylonjs/core/Lights/Shadows/shadowGeneratorSceneComponent';
export { GlowLayer } from '@babylonjs/core/Layers/glowLayer';
import '@babylonjs/core/Layers/effectLayerSceneComponent';
export { Ray } from '@babylonjs/core/Culling/ray';
export { SceneLoader, ImportMeshAsync, LoadAssetContainerAsync } from '@babylonjs/core/Loading/sceneLoader';
export { AnimationGroup } from '@babylonjs/core/Animations/animationGroup';
import '@babylonjs/core/Animations/animatable';
import '@babylonjs/core/Rendering/edgesRenderer';
import '@babylonjs/core/Rendering/outlineRenderer';
export { FxaaPostProcess } from '@babylonjs/core/PostProcesses/fxaaPostProcess';
import '@babylonjs/core/Engines/Extensions/engine.dynamicTexture';
import '@babylonjs/loaders/glTF/2.0/glTFLoader';
import '@babylonjs/loaders/glTF/2.0/Extensions/KHR_materials_emissive_strength';
import '@babylonjs/loaders/glTF/2.0/Extensions/KHR_texture_transform';
import '@babylonjs/loaders/glTF/2.0/Extensions/KHR_materials_pbrSpecularGlossiness';
import '@babylonjs/loaders/glTF/2.0/Extensions/KHR_mesh_quantization';
export { GLTFFileLoader } from '@babylonjs/loaders/glTF/glTFFileLoader';
export { default as RAPIER } from '@dimforge/rapier3d-compat';
